CREATE TABLE lims_ped_tax_hist 
( `lims_pedon_tax_hist_id` REAL,
	`taxonomic_edition` TEXT,
	`taxonomic_classification_date_id` REAL,
	`taxonomic_classifier_person_id` REAL,
	`taxonomic_classification_type` TEXT,
	`taxon_name` TEXT,
	`taxon_kind` TEXT,
	`series_status` TEXT,
	`taxonomic_classification_name` TEXT,
	`taxonomic_order` TEXT,
	`taxonomic_suborder` TEXT,
	`taxonomic_great_group` TEXT,
	`taxonomic_subgroup` TEXT,
	`taxonomic_family_particle_size` TEXT,
	`taxonomic_family_part_size_mod` TEXT,
	`taxonomic_family_c_e_act_class` TEXT,
	`taxonomic_family_reaction` TEXT,
	`taxonomic_family_temp_class` TEXT,
	`taxonomic_family_haht_mat_class` TEXT,
	`taxonomic_moisture_subclass` TEXT,
	`taxonomic_temp_regime` TEXT,
	`lims_pedon_id` REAL 
)
