CREATE TABLE project 
( `proj_id` REAL,
	`proj_type` TEXT,
	`proj_status` TEXT,
	`fiscal_year` REAL,
	`country_area_id` REAL,
	`state_admindiv_id` REAL,
	`proj_seq` REAL,
	`lab_proj_name` TEXT,
	`submit_proj_name` TEXT,
	`proj_priority` REAL,
	`proj_reimburse_ind` REAL,
	`reg_office_org_id` REAL,
	`mlra_office_org_id` REAL,
	`proj_submit_id` REAL,
	`proj_submit_date_id` REAL,
	`proj_coordinator_id` REAL,
	`proj_export_date_id` REAL,
	`proj_due_date_id` REAL,
	`proj_est_comp_date_id` REAL,
	`project_source` TEXT,
	`private_flag` REAL,
	`transfer_flag` REAL,
	`project_lock` REAL,
	`project_folder_path` TEXT,
	`note_flag` REAL,
	`proj_note` TEXT 
)
