---
title: "Untitled"
output: html_vignette
---

```{r setup, echo=FALSE, results='hide', warning=FALSE}
library(knitr, quietly=TRUE)
library(kableExtra, quietly=TRUE)
opts_chunk$set(message=FALSE, warning=FALSE, background='#F7F7F7', fig.retina=2, dev='png', tidy=FALSE, verbose=FALSE, fig.align='center')
options(width=100, stringsAsFactors=FALSE)
```


```{r}
library(knitr)
library(readr)
library(digest)
library(purrr)
library(DBI)
```

Notes:
   * `natural_key` is `labsampnum`
   * `result_source_key` is `layer_key`


```{r}
x <- read_csv('E:/temp/Chem_light.csv')
x <- as.data.frame(x)
```


```{r}
# convert rows to list elements
# this implicitly removes rownames
# much faster than split(x, 1:nrow(x))
xx <- transpose(x)

# performance the same as map_chr(xx, digest)
hash <- sapply(xx, digest)

# sort for RLE
idx <- order(hash)
r <- rle(hash[idx])

# locate hashes with more than 1 row
dupe.idx <- which(r$lengths > 1)

# find rows in source data within a small set of matching hashes
row.idx <- which(hash %in% r$values[dupe.idx[1:2]])

x[row.idx, ]

kable(x[row.idx, 1:9], row.names = FALSE)
```


```{r eval=FALSE}
db <- dbConnect(RSQLite::SQLite(), "E:/working_copies/lab-data-delivery/code/text-file-to-sqlite/KSSL-data.sqlite")


tbls <- dbListTables(db)
names(tbls) <- tbls

getData <- function(table_name, labsampnum) {
  q <- sprintf("SELECT * from %s where labsampnum = '%s';", table_name, labsampnum)

  res <- try(dbGetQuery(db, q), silent = TRUE)
  
  if(class(res) == 'try-error')
    res <- NULL
  
  return(res)
}


getPedonLabSampNum <- function(labsampnum) {
  
  q <- sprintf("SELECT pedlabsampnum FROM NCSS_Pedon_Taxonomy WHERE pedon_key IN (SELECT pedon_key from NCSS_Layer where labsampnum = '%s');", labsampnum)
  res <- dbGetQuery(db, q)
  
  return(res$pedlabsampnum)
}


# get a single layer of data
getData('NCSS_Layer', '89P00600')

# get this layer from all tables that have labsampnum
d <- lapply(tbls, getData, labsampnum='89P00600')


getPedonLabSampNum('89P00600')

fetchKSSL(pedlabsampnum = getPedonLabSampNum('89P00600'))

```


```{r}
prep.codes <- dbGetQuery(db, "SELECT * from NCSS_Preparation;")
kable(prep.codes, row.names = FALSE)
```


```{r}
# keep unique data only
y <- unique(x)

# duplication factor
d <- data.frame(original=nrow(x), unique=nrow(y), duplication.factor=nrow(x) / nrow(y))

kable(d, row.names = FALSE)
```


```{r}
# 
y <- y[order(y$natural_key), ]

kable(head(y), row.names = FALSE)

table(y$prep_code)
```

```{r}
tab <- table(y$natural_key)
idx <- which(tab > 1)

# > 1 prep / sample
z <- y[y$natural_key %in% names(idx), ]

```

```{r}
knitr::kable(head(z, 10)[, 1:5], row.names = FALSE)
```

