CREATE TABLE layer 
( `layer_key` REAL,
	`labsampnum` TEXT,
	`project_key` REAL,
	`site_key` REAL,
	`pedon_key` REAL,
	`layer_sequence` REAL,
	`layer_type` TEXT,
	`layer_field_label_1` TEXT,
	`layer_field_label_2` TEXT,
	`layer_field_label_3` TEXT,
	`hzn_top` REAL,
	`hzn_bot` REAL,
	`hzn_desgn_old` TEXT,
	`hzn_desgn` TEXT,
	`hzn_discontinuity` REAL,
	`hzn_master` TEXT,
	`hzn_prime` TEXT,
	`hzn_vert_subdvn` REAL,
	`hzn_desgn_other` TEXT,
	`non_hzn_desgn` TEXT,
	`stratified_textures_flag` REAL,
	`texture_description` TEXT 
)
