CREATE TABLE Mineralogy_Glass 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`analyzed_size_fr` TEXT,
	`min_BG_glass_cou` INTEGER,
	`min_DI_glass_cou` INTEGER,
	`min_GA_glass_cou` INTEGER,
	`min_GS_glass_cou` INTEGER,
	`min_FG_glass_cou` INTEGER,
	`min_GC_glass_cou` INTEGER,
	`min_HG_glass_cou` INTEGER,
	`min_OG_glass_cou` INTEGER,
	`min_QG_glass_cou` INTEGER,
	`min_GM_glass_cou` INTEGER,
	`min_OT_glass_cou` INTEGER,
	`min_PO_glass_cou` INTEGER,
	`min_SS_glass_cou` INTEGER,
	`min_AR_glass_cou` INTEGER,
	`tot_gr` INTEGER 
)
CREATE TABLE Mineralogy_Petro 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`analyzed_size_fr` TEXT,
	`min_AC_petro_cou` INTEGER,
	`min_FB_petro_cou` INTEGER,
	`min_AM_petro_cou` INTEGER,
	`min_AE_petro_cou` INTEGER,
	`min_AN_petro_cou` INTEGER,
	`min_FA_petro_cou` INTEGER,
	`min_AY_petro_cou` INTEGER,
	`min_FN_petro_cou` INTEGER,
	`min_FH_petro_cou` TEXT,
	`min_AH_petro_cou` INTEGER,
	`min_AG_petro_cou` INTEGER,
	`min_AP_petro_cou` INTEGER,
	`min_AO_petro_cou` INTEGER,
	`min_AF_petro_cou` TEXT,
	`min_AU_petro_cou` INTEGER,
	`min_BA_petro_cou` TEXT,
	`min_BG_petro_cou` INTEGER,
	`min_BY_petro_cou` INTEGER,
	`min_BT_petro_cou` INTEGER,
	`min_BC_petro_cou` INTEGER,
	`min_BE_petro_cou` TEXT,
	`min_BZ_petro_cou` TEXT,
	`min_BK_petro_cou` INTEGER,
	`min_BR_petro_cou` INTEGER,
	`min_CA_petro_cou` INTEGER,
	`min_CB_petro_cou` INTEGER,
	`min_CT_petro_cou` INTEGER,
	`min_CD_petro_cou` INTEGER,
	`min_CL_petro_cou` INTEGER,
	`min_CM_petro_cou` INTEGER,
	`min_CY_petro_cou` INTEGER,
	`min_QC_petro_cou` INTEGER,
	`min_CH_petro_cou` INTEGER,
	`min_CZ_petro_cou` INTEGER,
	`min_CC_petro_cou` INTEGER,
	`min_CO_petro_cou` INTEGER,
	`min_CN_petro_cou` INTEGER,
	`min_CR_petro_cou` INTEGER,
	`min_DI_petro_cou` INTEGER,
	`min_DP_petro_cou` INTEGER,
	`min_DL_petro_cou` INTEGER,
	`min_DU_petro_cou` INTEGER,
	`min_EN_petro_cou` INTEGER,
	`min_EP_petro_cou` INTEGER,
	`min_FD_petro_cou` INTEGER,
	`min_FZ_petro_cou` INTEGER,
	`min_FM_petro_cou` INTEGER,
	`min_FU_petro_cou` INTEGER,
	`min_FF_petro_cou` INTEGER,
	`min_GG_petro_cou` INTEGER,
	`min_GN_petro_cou` INTEGER,
	`min_GI_petro_cou` INTEGER,
	`min_GA_petro_cou` INTEGER,
	`min_FG_petro_cou` INTEGER,
	`min_GC_petro_cou` INTEGER,
	`min_HG_petro_cou` INTEGER,
	`min_OG_petro_cou` INTEGER,
	`min_QG_petro_cou` INTEGER,
	`min_GS_petro_cou` INTEGER,
	`min_GM_petro_cou` INTEGER,
	`min_GL_petro_cou` INTEGER,
	`min_GO_petro_cou` INTEGER,
	`min_GE_petro_cou` INTEGER,
	`min_GD_petro_cou` TEXT,
	`min_GY_petro_cou` INTEGER,
	`min_KH_petro_cou` INTEGER,
	`min_HE_petro_cou` INTEGER,
	`min_HN_petro_cou` INTEGER,
	`min_HB_petro_cou` INTEGER,
	`min_ID_petro_cou` INTEGER,
	`min_QI_petro_cou` INTEGER,
	`min_FE_petro_cou` INTEGER,
	`min_JO_petro_cou` INTEGER,
	`min_KK_petro_cou` INTEGER,
	`min_KY_petro_cou` INTEGER,
	`min_FL_petro_cou` INTEGER,
	`min_LA_petro_cou` INTEGER,
	`min_LP_petro_cou` TEXT,
	`min_LO_petro_cou` TEXT,
	`min_LU_petro_cou` INTEGER,
	`min_LM_petro_cou` INTEGER,
	`min_LT_petro_cou` TEXT,
	`min_ME_petro_cou` INTEGER,
	`min_MG_petro_cou` INTEGER,
	`min_MR_petro_cou` TEXT,
	`min_ML_petro_cou` INTEGER,
	`min_MI_petro_cou` INTEGER,
	`min_FC_petro_cou` INTEGER,
	`min_MZ_petro_cou` INTEGER,
	`min_MT_petro_cou` INTEGER,
	`min_MS_petro_cou` INTEGER,
	`min_NE_petro_cou` INTEGER,
	`min_NX_petro_cou` INTEGER,
	`min_FO_petro_cou` INTEGER,
	`min_OV_petro_cou` INTEGER,
	`min_OP_petro_cou` INTEGER,
	`min_FR_petro_cou` INTEGER,
	`min_OR_petro_cou` INTEGER,
	`min_OW_petro_cou` INTEGER,
	`min_OT_petro_cou` INTEGER,
	`min_PK_petro_cou` INTEGER,
	`min_PL_petro_cou` INTEGER,
	`min_PD_petro_cou` INTEGER,
	`min_FP_petro_cou` INTEGER,
	`min_PO_petro_cou` INTEGER,
	`min_PJ_petro_cou` TEXT,
	`min_PN_petro_cou` INTEGER,
	`min_FK_petro_cou` INTEGER,
	`min_PI_petro_cou` INTEGER,
	`min_PU_petro_cou` TEXT,
	`min_PY_petro_cou` INTEGER,
	`min_PR_petro_cou` INTEGER,
	`min_QZ_petro_cou` INTEGER,
	`min_RA_petro_cou` INTEGER,
	`min_MD_petro_cou` INTEGER,
	`min_RE_petro_cou` INTEGER,
	`min_RO_petro_cou` TEXT,
	`min_RB_petro_cou` TEXT,
	`min_RU_petro_cou` INTEGER,
	`min_FS_petro_cou` INTEGER,
	`min_SR_petro_cou` INTEGER,
	`min_SI_petro_cou` INTEGER,
	`min_SA_petro_cou` INTEGER,
	`min_SL_petro_cou` INTEGER,
	`min_SG_petro_cou` INTEGER,
	`min_SP_petro_cou` INTEGER,
	`min_SN_petro_cou` INTEGER,
	`min_SS_petro_cou` INTEGER,
	`min_SO_petro_cou` INTEGER,
	`min_ST_petro_cou` INTEGER,
	`min_SU_petro_cou` INTEGER,
	`min_TA_petro_cou` INTEGER,
	`min_TP_petro_cou` INTEGER,
	`min_TM_petro_cou` INTEGER,
	`min_TE_petro_cou` INTEGER,
	`min_VR_petro_cou` INTEGER,
	`min_VC_petro_cou` INTEGER,
	`min_VH_petro_cou` INTEGER,
	`min_VM_petro_cou` INTEGER,
	`min_VI_petro_cou` TEXT,
	`min_WV_petro_cou` TEXT,
	`min_AR_petro_cou` INTEGER,
	`min_WE_petro_cou` INTEGER,
	`min_ZE_petro_cou` INTEGER,
	`min_ZR_petro_cou` INTEGER,
	`min_ZO_petro_cou` INTEGER,
	`min_AI_petro_cou` TEXT,
	`min_AL_petro_cou` TEXT,
	`min_CE_petro_cou` TEXT,
	`min_HA_petro_cou` TEXT,
	`min_IL_petro_cou` INTEGER,
	`min_LC_petro_cou` INTEGER,
	`min_LE_petro_cou` TEXT,
	`min_LI_petro_cou` TEXT,
	`min_MC_petro_cou` TEXT,
	`min_MH_petro_cou` TEXT,
	`min_MM_petro_cou` TEXT,
	`min_MV_petro_cou` TEXT,
	`min_PA_petro_cou` INTEGER,
	`min_PG_petro_cou` TEXT,
	`min_SC_petro_cou` TEXT,
	`min_SE_petro_cou` TEXT,
	`min_SM_petro_cou` TEXT,
	`min_TD_petro_cou` TEXT,
	`min_TH_petro_cou` TEXT,
	`min_HY_petro_cou` INTEGER,
	`min_HS_petro_cou` TEXT,
	`min_HV_petro_cou` TEXT,
	`min_PM_petro_cou` TEXT,
	`resist_min_tot` INTEGER,
	`tot_gr` INTEGER 
)
CREATE TABLE Mineralogy_Thermal 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`analyzed_size_fr` TEXT,
	`min_GI_dsc` REAL,
	`min_KK_dsc` REAL,
	`min_GY_tga` REAL,
	`min_GI_tga` REAL,
	`min_GE_tga` REAL,
	`min_KK_tga` REAL,
	`min_GI_dta` REAL,
	`min_KK_dta` REAL,
	`min_GE_dta` REAL,
	`min_KH_dta` REAL,
	`min_QZ_dta` REAL 
)
CREATE TABLE Mineralogy_Xray 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`analyzed_size_fr` TEXT,
	`min_AM_xray` INTEGER,
	`min_LC_xray` INTEGER,
	`min_AE_xray` INTEGER,
	`min_AG_xray` INTEGER,
	`min_AO_xray` INTEGER,
	`min_BT_xray` INTEGER,
	`min_BC_xray` INTEGER,
	`min_BR_xray` INTEGER,
	`min_CA_xray` INTEGER,
	`min_CL_xray` INTEGER,
	`min_CM_xray` INTEGER,
	`min_CR_xray` INTEGER,
	`min_DL_xray` INTEGER,
	`min_EN_xray` INTEGER,
	`min_FD_xray` INTEGER,
	`min_GI_xray` INTEGER,
	`min_GL_xray` INTEGER,
	`min_GE_xray` INTEGER,
	`min_GY_xray` INTEGER,
	`min_KH_xray` INTEGER,
	`min_HE_xray` INTEGER,
	`min_HN_xray` INTEGER,
	`min_HB_xray` INTEGER,
	`min_IL_xray` INTEGER,
	`min_KK_xray` INTEGER,
	`min_FL_xray` INTEGER,
	`min_LE_xray` INTEGER,
	`min_MH_xray` INTEGER,
	`min_MG_xray` INTEGER,
	`min_MI_xray` INTEGER,
	`min_MT_xray` INTEGER,
	`min_MC_xray` INTEGER,
	`min_MM_xray` INTEGER,
	`min_MV_xray` INTEGER,
	`min_MS_xray` INTEGER,
	`min_NX_xray` INTEGER,
	`min_FO_xray` INTEGER,
	`min_FR_xray` INTEGER,
	`min_PG_xray` INTEGER,
	`min_PL_xray` INTEGER,
	`min_FP_xray` INTEGER,
	`min_FK_xray` INTEGER,
	`min_PY_xray` INTEGER,
	`min_QZ_xray` INTEGER,
	`min_RE_xray` TEXT,
	`min_SE_xray` INTEGER,
	`min_TA_xray` INTEGER,
	`min_TH_xray` INTEGER,
	`min_TD_xray` INTEGER,
	`min_VR_xray` INTEGER,
	`min_VC_xray` INTEGER,
	`min_VH_xray` INTEGER,
	`min_VM_xray` INTEGER,
	`min_ZE_xray` INTEGER,
	`min_HA_xray` INTEGER,
	`min_HS_xray` INTEGER,
	`min_HV_xray` INTEGER 
)
CREATE TABLE Miscellaneous_Data 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`ca_neutral_salt` REAL,
	`ca_kcl` REAL,
	`mg_neutral_salt` REAL,
	`mg_kcl` REAL,
	`cec_nac` REAL,
	`cec_bacl` REAL,
	`ca_mg_satx` REAL,
	`hco3_co3` REAL,
	`ph10_ca` REAL,
	`ph10_h2o` REAL,
	`sand_mcvc` REAL,
	`sand_mcvcc_NaOAc` REAL,
	`w1bl2fm` REAL,
	`w2bl2fm` REAL,
	`db_10b` REAL 
)
CREATE TABLE NCSS_Analysis_Procedure 
( `procedure_key` INTEGER,
	`procedure_name` TEXT,
	`requested_analys` TEXT,
	`procedure_abbrev` TEXT,
	`procedure_code` TEXT,
	`procedure_descri` TEXT,
	`SSIR_42_v_5_Page` INTEGER,
	`URL_to_SSIR_42_v` TEXT 
)
CREATE TABLE NCSS_Analyte 
( `analyte_key` INTEGER,
	`analyte_type` TEXT,
	`analyte_name` TEXT,
	`analyte_abbrev` TEXT,
	`analyte_code` TEXT,
	`analyte_data_typ` TEXT,
	`analyte_format` REAL,
	`uom_abbrev` TEXT,
	`analyte_source_t` TEXT,
	`analyte_agg_meth` TEXT,
	`analyte_algorith` TEXT,
	`analyte_desc` TEXT,
	`analyte_size_fra` TEXT 
)
CREATE TABLE NCSS_Data_Dictionary_Data_Tier 
( `data_tier_desc` TEXT,
	`column_index` INTEGER,
	`column_name` TEXT,
	`analyte_name` TEXT,
	`analyte_abbrev` TEXT,
	`analyte_code` TEXT,
	`analyte_type` TEXT,
	`analyte_data_typ` TEXT,
	`analyte_format` REAL,
	`uom_abbrev` TEXT,
	`analyte_desc` TEXT,
	`calc_size_frac` TEXT 
)
CREATE TABLE NCSS_Data_Dictionary_Layer_Pedon_Taxonomy_Site_Location 
( `table_name` TEXT,
	`column_seq` REAL,
	`column_name` TEXT,
	`column_desc` TEXT 
)
CREATE TABLE NCSS_Layer 
( `layer_key` INTEGER,
	`labsampnum` TEXT,
	`project_key` INTEGER,
	`site_key` INTEGER,
	`pedon_key` INTEGER,
	`layer_sequence` INTEGER,
	`layer_type` TEXT,
	`layer_field_labe` TEXT,
	`layer_field_la_1` TEXT,
	`layer_field_la_2` TEXT,
	`hzn_top` REAL,
	`hzn_bot` REAL,
	`hzn_desgn_old` TEXT,
	`hzn_desgn` TEXT,
	`hzn_discontinuit` INTEGER,
	`hzn_master` TEXT,
	`hzn_prime` TEXT,
	`hzn_vert_subdvn` INTEGER,
	`hzn_desgn_other` TEXT,
	`non_hzn_desgn` TEXT,
	`stratified_textu` INTEGER,
	`texture_descript` TEXT 
)
CREATE TABLE NCSS_Pedon_Calc 
( `pedon_key` INTEGER,
	`pedlabsampnum` TEXT,
	`cntrl_depth_to_t` INTEGER,
	`cntrl_depth_to_b` INTEGER,
	`nco3_clay_wtavg` REAL,
	`wf_0175_wtavg` REAL,
	`clay_tot_wtavg` REAL,
	`vfg2_wtavg` REAL,
	`COLEws_sum` REAL,
	`cec7_cly_wtavg` REAL 
)
CREATE TABLE NCSS_Pedon_Taxonomy 
( `pedon_key` INTEGER,
	`pedlabsampnum` TEXT,
	`pedoniid` INTEGER,
	`upedonid` TEXT,
	`site_key` INTEGER,
	`samp_name` TEXT,
	`samp_class_type` TEXT,
	`samp_classdate` REAL,
	`samp_classificat` TEXT,
	`samp_taxorder` TEXT,
	`samp_taxsuborder` TEXT,
	`samp_taxgrtgroup` TEXT,
	`samp_taxsubgrp` TEXT,
	`samp_taxpartsize` TEXT,
	`samp_taxpartsi_1` TEXT,
	`samp_taxfamhahat` TEXT,
	`samp_taxminalogy` TEXT,
	`samp_taxceactcl` TEXT,
	`samp_taxreaction` TEXT,
	`samp_taxtempcl` TEXT,
	`samp_taxmoistscl` TEXT,
	`samp_taxtempregi` TEXT,
	`samp_taxother` TEXT,
	`samp_osdtypelocf` INTEGER,
	`corr_name` TEXT,
	`corr_class_type` TEXT,
	`corr_classdate` REAL,
	`corr_classificat` TEXT,
	`corr_taxorder` TEXT,
	`corr_taxsuborder` TEXT,
	`corr_taxgrtgroup` TEXT,
	`corr_taxsubgrp` TEXT,
	`corr_taxpartsize` TEXT,
	`corr_taxpartsi_1` TEXT,
	`corr_taxfamhahat` TEXT,
	`corr_taxminalogy` TEXT,
	`corr_taxceactcl` TEXT,
	`corr_taxreaction` TEXT,
	`corr_taxtempcl` TEXT,
	`corr_taxmoistscl` TEXT,
	`corr_taxtempregi` TEXT,
	`corr_taxother` TEXT,
	`corr_osdtypelocf` INTEGER,
	`SSL_name` TEXT,
	`SSL_class_type` TEXT,
	`SSL_classdate` REAL,
	`SSL_classificati` TEXT,
	`SSL_taxorder` TEXT,
	`SSL_taxsuborder` TEXT,
	`SSL_taxgrtgroup` TEXT,
	`SSL_taxsubgrp` TEXT,
	`SSL_taxpartsize` TEXT,
	`SSL_taxpartsizem` TEXT,
	`SSL_taxfamhahatm` TEXT,
	`SSL_taxminalogy` TEXT,
	`SSL_taxceactcl` TEXT,
	`SSL_taxreaction` TEXT,
	`SSL_taxtempcl` TEXT,
	`SSL_taxmoistscl` TEXT,
	`SSL_taxtempregim` TEXT,
	`SSL_taxother` TEXT,
	`SSL_osdtypelocfl` TEXT,
	`cntrl_depth_to_t` REAL,
	`cntrl_depth_to_b` REAL,
	`pedon_completene` INTEGER,
	`latitude_decimal` REAL,
	`longitude_decima` REAL 
)
CREATE TABLE NCSS_Preparation 
( `prep_code` TEXT,
	`moisture_state` TEXT,
	`orig_size_frac` TEXT,
	`prep_desc` TEXT 
)
CREATE TABLE NCSS_Project 
( `project_key` INTEGER,
	`lab_proj_name` TEXT,
	`submit_proj_name` TEXT,
	`source_name` TEXT 
)
CREATE TABLE NCSS_Site_Location 
( `site_key` INTEGER,
	`siteiid` INTEGER,
	`usiteid` TEXT,
	`site_obsdate` TEXT,
	`latitude_decimal` REAL,
	`longitude_decima` REAL,
	`country_code` TEXT,
	`country_name` TEXT,
	`state_code` TEXT,
	`state_name` TEXT,
	`county_code` TEXT,
	`county_name` TEXT,
	`mlra_code` TEXT,
	`mlra_name` TEXT,
	`ssa_code` TEXT,
	`ssa_name` TEXT,
	`npark_code` TEXT,
	`npark_name` TEXT,
	`nforest_code` TEXT,
	`nforest_name` TEXT,
	`PedonName` TEXT,
	`PedonNameType` TEXT,
	`PedonClassType` TEXT 
)
CREATE TABLE Organic 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`min_lt2` REAL,
	`eom_tot_c` REAL,
	`eom_minlt2` REAL,
	`c_tot` REAL,
	`n_tot` REAL,
	`c_n_ra` REAL,
	`fib_urb` REAL,
	`fib_rb` REAL,
	`pyr_col` TEXT,
	`decomp_state` TEXT,
	`limnic_type` TEXT,
	`ph_hist` REAL,
	`ph_h2o` REAL,
	`db_3brw` REAL,
	`db_3rw` REAL,
	`db_od` REAL,
	`oc` REAL 
)
CREATE TABLE pH_and_Carbonates 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`ph_cacl2` REAL,
	`ph_h2o` REAL,
	`ph_kcl` REAL,
	`ph_naf` REAL,
	`ph_sp` REAL,
	`caco3` REAL,
	`caco3l20` REAL,
	`c_gypl2` REAL,
	`gypl20` REAL,
	`resist` REAL,
	`ph_ox` REAL,
	`ph_oxin` REAL 
)
CREATE TABLE Phosphorus 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`Melanic` REAL,
	`p_ox` REAL,
	`p_bray1` REAL,
	`p_bray2` TEXT,
	`p_olsn` REAL,
	`p_nz` REAL,
	`p_h2o` REAL,
	`p_citx` REAL,
	`p_mehlich3` REAL,
	`n_no3` REAL 
)
CREATE TABLE PSDA_and_Rock_Fragments 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`clay_tot_psa` REAL,
	`silt_tot_psa` REAL,
	`sand_tot_psa` REAL,
	`clay_f` REAL,
	`co3_cly` REAL,
	`silt_f_psa` REAL,
	`silt_c_psa` REAL,
	`sand_vf_psa` REAL,
	`sand_f_psa` REAL,
	`sand_m_psa` REAL,
	`sand_c_psa` REAL,
	`sand_vc_psa` REAL,
	`wf_25` REAL,
	`wf_520` REAL,
	`wf_2075` REAL,
	`wf_0175` REAL,
	`wpg2` REAL,
	`tex_psda` TEXT 
)
CREATE TABLE Rosetta_Parameters 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`theta_r` REAL,
	`theta_s` REAL,
	`alpha` REAL,
	`npar` REAL,
	`Ks` REAL,
	`Ko` REAL,
	`Lpar` REAL 
)
CREATE TABLE Salt 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`ca_satx` REAL,
	`mg_satx` REAL,
	`na_satx` REAL,
	`k_satx` REAL,
	`co3_satx` REAL,
	`hco3sx` REAL,
	`fl_satx` REAL,
	`cl_satx` REAL,
	`p_satx` REAL,
	`br_satx` REAL,
	`oac_satx` REAL,
	`so4_satx` REAL,
	`no2_satx` REAL,
	`no3_satx` REAL,
	`h2osatx` REAL,
	`te_salt` REAL,
	`ec_satp` REAL,
	`ec_12pre` REAL,
	`na_exch` REAL,
	`sar` REAL 
)
CREATE TABLE Supplementary_Tier_1 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`pps2` REAL,
	`pps32` REAL,
	`pps1` REAL,
	`pps34` REAL,
	`pps38` REAL,
	`pps4` REAL,
	`pps10` REAL,
	`pps40` REAL,
	`pps200` REAL,
	`pps20m` REAL,
	`pps5m` REAL,
	`pps2m` REAL,
	`cc1` REAL,
	`cc5` REAL,
	`cc25` REAL,
	`cc10` REAL,
	`cc05` REAL,
	`cc60p` REAL,
	`cc50p` REAL,
	`cc10p` REAL,
	`abgll` TEXT,
	`abgpi` TEXT,
	`g_ufrmty` REAL,
	`g_crvtur` REAL 
)
CREATE TABLE Supplementary_Tier_2 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`wpg2` REAL,
	`wp250u` REAL,
	`wp25075` REAL,
	`wp752` REAL,
	`wp7520` REAL,
	`wp205` REAL,
	`wp52` REAL,
	`wpl2` REAL,
	`wf_275` REAL,
	`wf_2075` REAL,
	`wf_520` REAL,
	`wf_25` REAL,
	`wf_l2` REAL,
	`db_13bw` REAL,
	`db_13bw_basis` TEXT,
	`db_odw` REAL,
	`db_fmstw` REAL,
	`db_satw` REAL,
	`db_13b` REAL,
	`db_3rw` TEXT,
	`db_3est` TEXT,
	`db_15b` REAL,
	`db_od` REAL,
	`db_13bm` REAL,
	`db_sat` REAL,
	`vr_13w` REAL,
	`vr_13l2` REAL 
)
CREATE TABLE Supplementary_Tier_3 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`vfg2` REAL,
	`vf250u` REAL,
	`vf25075` REAL,
	`vf752` REAL,
	`vf7520` REAL,
	`vf205` REAL,
	`vf52` REAL,
	`vfl2` REAL,
	`vft205` REAL,
	`vft05002` REAL,
	`vftl002` REAL,
	`po_drn13` REAL,
	`po_fil13` REAL,
	`c_n_ra` REAL,
	`fcly_cly` REAL,
	`cec8_cly` REAL,
	`CECSCT` REAL,
	`cec7_cly_cec1` REAL,
	`w15cly` REAL,
	`lep_cly` REAL,
	`le_315w` REAL,
	`le_d3w` REAL,
	`le_315l2` REAL,
	`le_d3l2` REAL,
	`wrd_ws13` REAL,
	`wrd_l2` REAL 
)
CREATE TABLE Supplementary_Tier_4 
( `labsampnum` TEXT,
	`result_source_ke` INTEGER,
	`prep_code` TEXT,
	`cfg2` REAL,
	`cf752` REAL,
	`cf202` REAL,
	`cf205` REAL,
	`cf05002` REAL,
	`cfl002` REAL,
	`cffvcsa` REAL,
	`cffcsa` REAL,
	`cffmsa` REAL,
	`cfffsa` REAL,
	`cffvfsa` REAL,
	`cffcsi` REAL,
	`cfffsi` REAL,
	`cffcly` REAL,
	`tex_psda` TEXT,
	`sand_tot_psa` REAL,
	`silt_tot_psa` REAL,
	`clay_tot_psa` REAL,
	`ph_cacl2` REAL,
	`resist` REAL,
	`ec_satp` REAL 
)
