CREATE TABLE area 
( `areasymbol` TEXT,
	`areaname` TEXT,
	`areaacres` TEXT,
	`obterm` TEXT,
	`areatypeiidref` TEXT,
	`recwlupdated` TEXT,
	`areaiid` TEXT 
)
CREATE TABLE areatype 
( `areatypename` TEXT,
	`atdbiidref` TEXT,
	`recwlupdated` TEXT,
	`areatypeiid` TEXT 
)
CREATE TABLE basalareatreescounted 
( `plotspeciebasala` TEXT,
	`seqnum` TEXT,
	`treenumber` TEXT,
	`treeheight` TEXT,
	`treediameterbrea` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`basalareatreesco` TEXT 
)
CREATE TABLE beltdata 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`plantheightcllow` TEXT,
	`plantheightclupp` TEXT,
	`plantcount` TEXT,
	`speciesdensity` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`beltdataiid` TEXT 
)
CREATE TABLE belttransectsummary 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`plantheightcllow` TEXT,
	`plantheightclupp` TEXT,
	`plantcounttotal` TEXT,
	`htclassplantdens` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`belttranssummiid` TEXT 
)
CREATE TABLE comparativeyielddata 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`yieldrank` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`compyielddataiid` TEXT 
)
CREATE TABLE comparativeyieldrefquadrats 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`refyieldrank` TEXT,
	`quadratsize` TEXT,
	`quadratshape` TEXT,
	`clippedwtrefquad` TEXT,
	`compyldconvfacto` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`compyldrefquadii` TEXT 
)
CREATE TABLE croptreedetails 
( `croptreesummiidr` TEXT,
	`seqnum` TEXT,
	`treenumber` TEXT,
	`plantiidref` TEXT,
	`treediameterbrea` TEXT,
	`croptreeprimaryc` TEXT,
	`croptreesecondar` TEXT,
	`cuttreeindicator` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`croptreedetailsi` TEXT 
)
CREATE TABLE croptreesubplotdetails 
( `croptreesummiidr` TEXT,
	`seqnum` TEXT,
	`subplotnumber` TEXT,
	`leavetreebasalar` TEXT,
	`cuttreebasalarea` TEXT,
	`basalareasubplot` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`croptreesubplotd` TEXT 
)
CREATE TABLE croptreesummary 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`treecounttotal` TEXT,
	`currenttreedensi` TEXT,
	`currentbasalarea` TEXT,
	`currentplotavedb` TEXT,
	`cuttreebasalarea` TEXT,
	`leavetreebasalar` TEXT,
	`cuttreecount` TEXT,
	`cuttreedensity` TEXT,
	`cuttreeavedbh` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`croptreesummaryi` TEXT 
)
CREATE TABLE croptreetotals 
( `croptreesummiidr` TEXT,
	`seqnum` TEXT,
	`croptreeprimaryc` TEXT,
	`categorytreecoun` TEXT,
	`categorytreedens` TEXT,
	`categorydbhave` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`croptreetotalsii` TEXT 
)
CREATE TABLE daubenmirecancovclasssumm 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`daubcancovclass` TEXT,
	`cancovclassmidpo` TEXT,
	`cancovclasscount` TEXT,
	`cancovproduct` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`daubcancovclsumm` TEXT 
)
CREATE TABLE daubenmirecancovquaddetail 
( `daubcancovclsumm` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`daubcancovquadde` TEXT 
)
CREATE TABLE densityquadratdetails 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`maturecount` TEXT,
	`maturedensitycla` TEXT,
	`seedlingcount` TEXT,
	`seedlingdensityc` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`densityquaddetai` TEXT 
)
CREATE TABLE dwrquadratdetails 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`dwrone` TEXT,
	`dwrtwo` TEXT,
	`dwrthree` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`dwrquaddetailsii` TEXT 
)
CREATE TABLE ecologicalsite 
( `ecositeid` TEXT,
	`ecositenm` TEXT,
	`ecositeorigin` TEXT,
	`obterm` TEXT,
	`ecositedbiidref` TEXT,
	`recwlupdated` TEXT,
	`ecositeiid` TEXT 
)
CREATE TABLE frequencyquadratdetails 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`speciespresentin` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`freqquaddetailsi` TEXT 
)
CREATE TABLE groundcovdetails 
( `transectgrcoviid` TEXT,
	`seqnum` TEXT,
	`transectpointloc` TEXT,
	`quadratnumber` TEXT,
	`quadratcoverpct` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`groundcovdetails` TEXT 
)
CREATE TABLE groundsurfcovdetails 
( `transectgrsurfco` TEXT,
	`seqnum` TEXT,
	`transectpointloc` TEXT,
	`quadratnumber` TEXT,
	`quadratcoverpct` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`groundsurfcovdet` TEXT 
)
CREATE TABLE MetadataCardinality 
( `Cardinality` INTEGER,
	`CardinalityName` TEXT 
)
CREATE TABLE MetadataColumnLookup 
( `TableID` INTEGER,
	`ColumnID` INTEGER,
	`TableColumnSeque` INTEGER,
	`RelationshipID` INTEGER,
	`DisplaySequence` INTEGER,
	`Branch` INTEGER,
	`DisplayTableID` INTEGER,
	`DisplayColumnID` INTEGER,
	`DisplayTableColu` INTEGER,
	`DisplayColumnLab` TEXT,
	`DisplayOnlyInCho` INTEGER 
)
CREATE TABLE MetadataDomainDetail 
( `domain_id` REAL,
	`choice_sequence` REAL,
	`choice_id` REAL,
	`choice` TEXT,
	`choice_label` TEXT,
	`choice_obsolete` INTEGER,
	`choice_acronym` TEXT,
	`fieldSize` INTEGER 
)
CREATE TABLE MetadataIndexDetail 
( `IndexID` INTEGER,
	`IndexColumnSeque` INTEGER,
	`TableID` INTEGER,
	`ColumnID` INTEGER,
	`TableColumnSeque` INTEGER 
)
CREATE TABLE MetadataRelationshipDetail 
( `RelationshipID` INTEGER,
	`LeftTableID` INTEGER,
	`LeftColumnID` INTEGER,
	`LeftTableColumnS` INTEGER,
	`RightTableID` INTEGER,
	`RightColumnID` INTEGER,
	`RightTableColumn` INTEGER,
	`LeftTable_TableN` TEXT,
	`LeftTable_FieldN` TEXT,
	`RightTable_Table` TEXT,
	`RightTable_Field` TEXT 
)
CREATE TABLE MetadataRelationshipMaster 
( `RelationshipID` INTEGER,
	`LeftTableID` INTEGER,
	`RightTableID` INTEGER,
	`RelationshipName` TEXT,
	`ForeignKeyConstr` TEXT,
	`Cardinality` INTEGER,
	`CardinalityMinim` INTEGER,
	`CardinalityMaxim` INTEGER,
	`Mandatory` INTEGER,
	`DeleteFail` INTEGER,
	`InHierarchy` INTEGER,
	`FavoriteChild` INTEGER,
	`LoadFindRelated` INTEGER,
	`Paste` INTEGER,
	`ConstraintDeferr` INTEGER 
)
CREATE TABLE MetadataTable 
( `TableID` TEXT,
	`TablePhysicalNam` TEXT,
	`TableLogicalName` TEXT,
	`TableLabel` TEXT,
	`TableDescription` TEXT,
	`ImportExportFile` TEXT,
	`TableCollectionI` INTEGER,
	`DAGLevel` INTEGER,
	`Visible` INTEGER,
	`Selectable` INTEGER,
	`Editable` INTEGER,
	`NoInsertOrDelete` INTEGER,
	`RootTable` INTEGER,
	`CreateAsView` INTEGER,
	`ClientDatabaseOn` INTEGER,
	`ServerDatabaseOn` INTEGER 
)
CREATE TABLE MetadataTableColumn 
( `TableID` TEXT,
	`ColumnID` TEXT,
	`TableColumnSeque` INTEGER,
	`BaseColumnPhysic` TEXT,
	`ColumnPhysicalNa` TEXT,
	`ColumnLogicalNam` TEXT,
	`ColumnGroupLabel` TEXT,
	`ColumnLabel` TEXT,
	`PhysicalDataType` INTEGER,
	`LogicalDataType` INTEGER,
	`DomainID` INTEGER,
	`ColumnDescriptio` TEXT,
	`ColumnHelpText` TEXT,
	`FieldSize` TEXT,
	`DecimalPrecision` TEXT,
	`DatetimePrecisio` TEXT,
	`Minimum` REAL,
	`Maximum` REAL,
	`DefaultType` INTEGER,
	`DefaultValue` TEXT,
	`Alignment` INTEGER,
	`DisplaySize` INTEGER,
	`SortSequence` INTEGER,
	`SortType` TEXT,
	`SortDirection` TEXT,
	`UnitsOfMeasureUn` TEXT,
	`UnitsOfMeasureAb` TEXT,
	`NotNull` INTEGER,
	`Visible` INTEGER,
	`Protected` INTEGER,
	`SetDefaultOnObje` INTEGER,
	`SetDefaultOnRowC` INTEGER,
	`IncludeInReplica` INTEGER,
	`FileContentColum` INTEGER,
	`maxFieldSize` INTEGER,
	`TableName` TEXT 
)
CREATE TABLE ncsslayerlabdata 
( `ncsspedonlabdata` INTEGER,
	`layerseqnum` INTEGER,
	`labsampnum` TEXT,
	`hzdept` INTEGER,
	`hzdepb` INTEGER,
	`layertype` TEXT,
	`hzname` TEXT,
	`hznameoriginal` TEXT,
	`stratextsflag` TEXT,
	`moistprepstate` TEXT,
	`texcl` TEXT,
	`sandvcmeasured` REAL,
	`sandcomeasured` REAL,
	`sandmedmeasured` REAL,
	`sandfinemeasured` REAL,
	`sandvfmeasured` REAL,
	`sandtotmeasured` REAL,
	`siltcomeasured` REAL,
	`siltfinemeasured` REAL,
	`silttotmeasured` REAL,
	`claycarbmeasured` REAL,
	`clayfinemeasured` REAL,
	`claytotmeasured` REAL,
	`carbonorganicpct` REAL,
	`carbontotalpctme` REAL,
	`ompctest` REAL,
	`fiberrubbedpct` INTEGER,
	`fiberunrubbedpct` INTEGER,
	`fragwt25` INTEGER,
	`fragwt520` INTEGER,
	`fragwt2075` INTEGER,
	`fragwt275` INTEGER,
	`wtpct0175` INTEGER,
	`wtpctgt2ws` INTEGER,
	`ph1to1h2o` REAL,
	`ph01mcacl2` REAL,
	`phnaf` REAL,
	`phoxidized` REAL,
	`resistivity` INTEGER,
	`ecmeasured` REAL,
	`esp` INTEGER,
	`sar` REAL,
	`cecsumcations` REAL,
	`cec7` REAL,
	`ecec` REAL,
	`sumbases` REAL,
	`basesatsumcation` INTEGER,
	`basesatnh4oac` INTEGER,
	`caco3equivmeasur` INTEGER,
	`caco3lt20measure` TEXT,
	`gypsumequivlt2me` INTEGER,
	`gypsumequivmeasu` INTEGER,
	`feoxalatemeasure` REAL,
	`feextractable` REAL,
	`fetotal` REAL,
	`sioxalatemeasure` REAL,
	`extracid` REAL,
	`extral` REAL,
	`aloxalatemeasure` REAL,
	`altotal` INTEGER,
	`pmehlich3` REAL,
	`ph2osolublemeasu` REAL,
	`poxalatemeasured` REAL,
	`polsenmeasured` REAL,
	`ptotalmeasured` INTEGER,
	`nzpretention` REAL,
	`dbthirdbar` REAL,
	`dbovendry` REAL,
	`aggstabpct` INTEGER,
	`wtenthbarclod` REAL,
	`wtenthbarsieve` REAL,
	`wthirdbarclod` REAL,
	`wthirdbarsieve` REAL,
	`wfifteenbarmeasu` REAL,
	`wretentiondiffws` REAL,
	`wfifteenbartocla` REAL,
	`adod` REAL,
	`lep` REAL,
	`cole` REAL,
	`liquidlimitmeasu` REAL,
	`pi` REAL,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`ncsslayerlabdata` INTEGER 
)
CREATE TABLE ncsspedonlabdata 
( `pedlabsampnum` TEXT,
	`peiidref` INTEGER,
	`psctopdepth` INTEGER,
	`psctopdepth_s` INTEGER,
	`pscbotdepth` INTEGER,
	`pscbotdepth_s` INTEGER,
	`noncarbclaywtavg` REAL,
	`claytotwtavg` REAL,
	`le0to100` REAL,
	`wf0175wtavgpsc` REAL,
	`volfractgt2wtavg` REAL,
	`cec7clayratiowta` REAL,
	`labdatasheeturl` TEXT,
	`ncsspedbiidref` INTEGER,
	`grpiidref` INTEGER,
	`objwlupdated` TEXT,
	`objuseriidref` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`ncsspedonlabdata` INTEGER 
)
CREATE TABLE nestedfreqquadratdetails 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`smallestquadrati` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`nestedfreqquadde` TEXT 
)
CREATE TABLE nestedfrequencysummary 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`subquadratnumber` TEXT,
	`subquadratsize` TEXT,
	`subquadrathitcou` TEXT,
	`subquadratspecie` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`nestedfreqsummar` TEXT 
)
CREATE TABLE pediagfeatures 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`featdept` INTEGER,
	`featdepb` INTEGER,
	`featthick_l` INTEGER,
	`featthick_r` INTEGER,
	`featthick_h` INTEGER,
	`featkind` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pediagfeatiid` INTEGER 
)
CREATE TABLE pedon 
( `siteobsiidref` INTEGER,
	`upedonid` TEXT,
	`pedrecorigin` TEXT,
	`descname` TEXT,
	`taxonname` TEXT,
	`taxonname_s` INTEGER,
	`localphase` TEXT,
	`taxclname` TEXT,
	`taxclname_s` INTEGER,
	`taxonkind` TEXT,
	`taxonkind_s` INTEGER,
	`pedontype` TEXT,
	`pedonpurpose` TEXT,
	`pedonunit` INTEGER,
	`labdatadescflag` TEXT,
	`relexpsize` INTEGER,
	`relexpuom` TEXT,
	`earthcovkind1` TEXT,
	`earthcovkind2` TEXT,
	`erocl` TEXT,
	`labsourceid` TEXT,
	`pedlabsampnum` TEXT,
	`tsectiidref` INTEGER,
	`tsectstopnum` INTEGER,
	`tsectinterval` REAL,
	`rcapointnumber` INTEGER,
	`soilreplicatenum` INTEGER,
	`azimuthfromplotc` INTEGER,
	`distancefromplot` REAL,
	`rectangularplotl` INTEGER,
	`distancefrombase` REAL,
	`pedodermclass` TEXT,
	`pedodermcovind` INTEGER,
	`biolcrusttypedom` TEXT,
	`biolcrusttypesec` TEXT,
	`physcrustsubtype` TEXT,
	`crustdevcl` TEXT,
	`rangevegcanopyty` TEXT,
	`rangevegcanopy_1` TEXT,
	`forestoverstoryv` TEXT,
	`forestunderstory` TEXT,
	`forestgroundcovv` TEXT,
	`forestgroundco_1` TEXT,
	`agronomicfeature` TEXT,
	`otherfeaturedesc` TEXT,
	`currentcropname` TEXT,
	`littercoverpct` INTEGER,
	`residuedescripti` TEXT,
	`pedonhydricratin` TEXT,
	`pecertstatus` TEXT,
	`peqcstatus` TEXT,
	`peqastatus` TEXT,
	`saspipelengthtot` REAL,
	`saspipelengthext` REAL,
	`saspipelengthunf` REAL,
	`sascoresettlemen` REAL,
	`sascorelength` REAL,
	`sascorestoragesi` TEXT,
	`sasexposurebegin` TEXT,
	`sasexposureend` TEXT,
	`pedbiidref` INTEGER,
	`grpiidref` INTEGER,
	`objwlupdated` TEXT,
	`objuseriidref` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`peiid` INTEGER 
)
CREATE TABLE pedondbcolumnmetadata 
( `pedondbtableid` INTEGER,
	`pedondbcolumnid` INTEGER,
	`pedondbcolumnseq` INTEGER,
	`pedondbcolumnnam` TEXT,
	`ipdiagmsgcolumnl` TEXT 
)
CREATE TABLE pedondbtablemetadata 
( `pedondbtableid` INTEGER,
	`pedondbtablename` TEXT,
	`pedondbobjectnam` TEXT,
	`ipdiagmsgtablela` TEXT,
	`ipdiagmsgsqlstmt` TEXT 
)
CREATE TABLE pefmp 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`fmpname` TEXT,
	`fmpvalue` REAL,
	`fmpunits` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pefmpiid` INTEGER 
)
CREATE TABLE pehydricfieldindicator 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`hydricsoilfieldi` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pehydricfieldind` INTEGER 
)
CREATE TABLE peinfiltrationch 
( `peinfilsumiidref` INTEGER,
	`testdate` TEXT,
	`repnum` INTEGER,
	`infiltrationmeas` REAL,
	`infiltrationring` TEXT,
	`ringinsertiondep` REAL,
	`ringradius` REAL,
	`waterponddepth` REAL,
	`mariottebottlera` TEXT,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`peinfilconsthead` INTEGER 
)
CREATE TABLE peinfiltrationchdata 
( `peinfilconsthead` TEXT,
	`infiltrationrunn` TEXT,
	`waterdrop` TEXT,
	`deltatime` TEXT,
	`infiltrationmeas` TEXT,
	`steadystateflag` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`peinfilchdataiid` TEXT 
)
CREATE TABLE peinfiltrationfh 
( `peinfilsumiidref` INTEGER,
	`testdate` TEXT,
	`repnum` INTEGER,
	`infiltrationmeas` REAL,
	`infiltrationring` TEXT,
	`ringinsertiondep` REAL,
	`ringradius` REAL,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`peinfilfallheadi` INTEGER 
)
CREATE TABLE peinfiltrationfhdata 
( `peinfilfallheadi` INTEGER,
	`infiltrationrunn` INTEGER,
	`deltatime` REAL,
	`infiltrationwate` REAL,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pedoninfilfhdata` INTEGER 
)
CREATE TABLE peinfiltrationsummary 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`testdate` TEXT,
	`datacollector` TEXT,
	`infiltrationmean` REAL,
	`infiltrationstdd` REAL,
	`infiltrationtest` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pedoninfilsumiid` INTEGER 
)
CREATE TABLE pepenetrationresistance 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`penetrometerdept` INTEGER,
	`obssoimoiststat` TEXT,
	`penetrometertipt` TEXT,
	`penetrometerspri` TEXT,
	`penetorient` TEXT,
	`penetrometerread` REAL,
	`penetrometerre_1` REAL,
	`penetrometerre_2` REAL,
	`penetrometerre_3` REAL,
	`datacollector` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pepenetrometerii` INTEGER 
)
CREATE TABLE perestrictions 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`resdept` INTEGER,
	`resdepb` INTEGER,
	`resthk_l` INTEGER,
	`resthk_r` INTEGER,
	`resthk_h` INTEGER,
	`reskind` TEXT,
	`reshard` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`perestrictiid` INTEGER 
)
CREATE TABLE pesoilstability 
( `peiidref` INTEGER,
	`seqnum` TEXT,
	`soilstabilitydep` REAL,
	`samplecollector` TEXT,
	`datacollector` TEXT,
	`testdate` TEXT,
	`soilstabilitycla` TEXT,
	`soilstabilityc_1` TEXT,
	`soilstabilityc_2` TEXT,
	`soilstabilityc_3` TEXT,
	`soilhydrophobici` INTEGER,
	`soilhydrophobi_1` INTEGER,
	`soilhydrophobi_2` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pesoilstabilityi` INTEGER 
)
CREATE TABLE petaxhistfmmin 
( `pedtaxhistoryiid` INTEGER,
	`seqnum` INTEGER,
	`minorder` INTEGER,
	`taxminalogy` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`petaxfmminiid` INTEGER 
)
CREATE TABLE petaxhistmoistcl 
( `pedtaxhistoryiid` INTEGER,
	`seqnum` INTEGER,
	`taxmoistcl` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`petaxmciid` INTEGER 
)
CREATE TABLE petaxhistory 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`classdate` TEXT,
	`classtype` TEXT,
	`classifier` TEXT,
	`taxonname` TEXT,
	`localphase` TEXT,
	`taxonkind` TEXT,
	`seriesstatus` TEXT,
	`taxclname` TEXT,
	`taxclname_s` INTEGER,
	`taxorder` TEXT,
	`taxsuborder` TEXT,
	`taxgrtgroup` TEXT,
	`taxsubgrp` TEXT,
	`taxpartsize` TEXT,
	`taxpartsizemod` TEXT,
	`taxceactcl` TEXT,
	`taxreaction` TEXT,
	`taxtempcl` TEXT,
	`taxmoistscl` TEXT,
	`taxtempregime` TEXT,
	`taxfamhahatmatcl` TEXT,
	`soiltaxedition` TEXT,
	`psctopdepth` INTEGER,
	`pscbotdepth` INTEGER,
	`osdtypelocflag` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`petaxhistoryiid` INTEGER 
)
CREATE TABLE petext 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`recdate` TEXT,
	`recauthor` TEXT,
	`pedontextkind` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`petextiid` INTEGER 
)
CREATE TABLE petxhistfmother 
( `pedtaxhistoryiid` INTEGER,
	`seqnum` INTEGER,
	`taxfamother` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`petaxfoiid` INTEGER 
)
CREATE TABLE phcemagent 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`ruprescem` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phcemagentiid` INTEGER 
)
CREATE TABLE phcoledata 
( `phlabresultiidre` INTEGER,
	`seqnum` TEXT,
	`repnum` INTEGER,
	`phcolereading` REAL,
	`phcolemethod` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phcoledataiid` INTEGER 
)
CREATE TABLE phcolor 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`colorpct` INTEGER,
	`colorhue` TEXT,
	`colorvalue` REAL,
	`colorchroma` INTEGER,
	`colorphysst` TEXT,
	`colormoistst` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phcoloriid` INTEGER 
)
CREATE TABLE phconccolor 
( `phconceniidref` INTEGER,
	`seqnum` INTEGER,
	`colorpct` INTEGER,
	`colorhue` TEXT,
	`colorvalue` REAL,
	`colorchroma` INTEGER,
	`colormoistst` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phconcencoloriid` INTEGER 
)
CREATE TABLE phconcs 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`concpct` INTEGER,
	`concsize` TEXT,
	`conccntrst` TEXT,
	`conchardness` TEXT,
	`concshape` TEXT,
	`conckind` TEXT,
	`conclocation` TEXT,
	`concboundary` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phconceniid` INTEGER 
)
CREATE TABLE phcracks 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`crackfreq` INTEGER,
	`crackkind` TEXT,
	`crackdepth` REAL,
	`crackwidth` REAL,
	`crackextabove` INTEGER,
	`crackextbelow` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phcracksiid` INTEGER 
)
CREATE TABLE phdb 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`bddepthtop` INTEGER,
	`bddepthbottom` INTEGER,
	`bdmethod` TEXT,
	`datacollector` TEXT,
	`samplevolfieldmo` REAL,
	`totalsamplewtfm` REAL,
	`totalsamplewtair` REAL,
	`coarsefragwtfm` REAL,
	`coarsefragwtaird` REAL,
	`coarsefragdensit` REAL,
	`coarsefragvolmea` REAL,
	`subsamplewtairdr` REAL,
	`subsamplewtod` REAL,
	`obsgrsoimoist` INTEGER,
	`obsgrsoimoist_s` INTEGER,
	`obsgravsoilmoist` INTEGER,
	`obsgravsoilmoi_1` INTEGER,
	`bdfieldmoistfine` REAL,
	`bdfieldmoistwhol` REAL,
	`bdovendrywhole` REAL,
	`bdovendrywhole_s` INTEGER,
	`bdovendryfineear` REAL,
	`bdovendryfinee_1` INTEGER,
	`bdsatiated` REAL,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phbulkdensityiid` INTEGER 
)
CREATE TABLE phdbcompliantcavity 
( `phbulkdensityiid` INTEGER,
	`bulkdensitycavit` TEXT,
	`bulkdensitycav_1` TEXT,
	`bulkdensitycav_2` TEXT,
	`bulkdensitycav_3` REAL,
	`bulkdensitycav_4` INTEGER,
	`bulkdensitycav_5` REAL,
	`bulkdensitycav_6` INTEGER,
	`cavityavedepthpr` TEXT,
	`cavityavedepthpo` TEXT,
	`bulkdensitycav_7` REAL,
	`bulkdensitycav_8` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phbulkdencavityi` INTEGER 
)
CREATE TABLE phdbcore 
( `phbulkdensityiid` INTEGER,
	`sampletubelength` REAL,
	`unfilledtubeleng` REAL,
	`unfilledtubele_1` INTEGER,
	`coresamplelength` REAL,
	`coresampleleng_1` INTEGER,
	`sampletubediamet` REAL,
	`coresamplevolume` REAL,
	`coresamplevolu_1` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phbulkdencoreiid` INTEGER 
)
CREATE TABLE phdbcorereading 
( `phbulkdencoreiid` INTEGER,
	`bulkdensitytubeh` REAL,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phbdcorereadingi` INTEGER 
)
CREATE TABLE phdbscoop 
( `phbulkdensityiid` INTEGER,
	`scooplength` REAL,
	`scoopwidth` REAL,
	`scoopdepthtotal` REAL,
	`scoopvolume` REAL,
	`scoopvolume_s` INTEGER,
	`scoopdepthunfill` REAL,
	`scoopdepthunfi_1` INTEGER,
	`scoopsamplevolum` REAL,
	`scoopsamplevol_1` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phbulkdenscoopii` INTEGER 
)
CREATE TABLE phdbscoopreading 
( `phbulkdenscoopii` INTEGER,
	`scoopheadspace` REAL,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phbulkdenscoopre` INTEGER 
)
CREATE TABLE phdesgnsuffix 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`desgnsuffix` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phdesgnsfxiid` INTEGER 
)
CREATE TABLE phfeatcolor 
( `phfeatsiidref` INTEGER,
	`seqnum` INTEGER,
	`colorpct` INTEGER,
	`colorhue` TEXT,
	`colorvalue` REAL,
	`colorchroma` INTEGER,
	`colormoistst` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phfeatcoloriid` INTEGER 
)
CREATE TABLE phfeatures 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`horfeatkind` TEXT,
	`horfeatvtpct_l` INTEGER,
	`horfeatvtpct_r` INTEGER,
	`horfeatvtpct_h` INTEGER,
	`horfeatlapct_l` INTEGER,
	`horfeatlapct_r` INTEGER,
	`horfeatlapct_h` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phfeatsiid` INTEGER 
)
CREATE TABLE phfmp 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`fmpname` TEXT,
	`fmpvalue` REAL,
	`fmpunits` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phfmpiid` INTEGER 
)
CREATE TABLE phfrags 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`fragvol` REAL,
	`fragweight` REAL,
	`fragsize_l` INTEGER,
	`fragsize_r` INTEGER,
	`fragsize_h` INTEGER,
	`fragkind` TEXT,
	`fragshp` TEXT,
	`fraground` TEXT,
	`fraghard` TEXT,
	`fragestmethod` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phfragsiid` INTEGER 
)
CREATE TABLE phgrcountdata 
( `phgrcountsumiidr` TEXT,
	`testdate` TEXT,
	`repnum` TEXT,
	`phgrcounttotal` TEXT,
	`phgrcountquartz` TEXT,
	`phgrcountmica` TEXT,
	`phgrcountglass` TEXT,
	`phgrcountglassco` TEXT,
	`phgrcountglassag` TEXT,
	`phgrcountother` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`phgrcountiid` TEXT 
)
CREATE TABLE phgrcountsummary 
( `phlabresultiidre` INTEGER,
	`seqnum` TEXT,
	`phgrcountquartz` INTEGER,
	`phgrcountmica` INTEGER,
	`phgrcountglass` INTEGER,
	`phgrcountglassco` INTEGER,
	`phgrcountglassag` TEXT,
	`phgrcountother` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phgrcountsumiid` INTEGER 
)
CREATE TABLE phhuarts 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`huartvol` INTEGER,
	`huartsize_l` INTEGER,
	`huartsize_r` INTEGER,
	`huartsize_h` INTEGER,
	`huartkind` TEXT,
	`huartco` TEXT,
	`huartshp` TEXT,
	`huartrnd` TEXT,
	`huartpen` TEXT,
	`huartsafety` TEXT,
	`huartper` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phhuartiid` INTEGER 
)
CREATE TABLE phhydrometeranalysis 
( `phlabresultiidre` INTEGER,
	`seqnum` INTEGER,
	`testdate` TEXT,
	`hydrosamplewt` REAL,
	`hydroshmpconc` REAL,
	`hydroblankread` REAL,
	`hydromethod` TEXT,
	`obsgrsoimoist` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phhydromanalysis` INTEGER 
)
CREATE TABLE phhydrometerdata 
( `phhydromanalysis` INTEGER,
	`hydroreadingnum` INTEGER,
	`deltatime` REAL,
	`hydrotemp` REAL,
	`hydroreading` REAL,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phhydrometerdata` INTEGER 
)
CREATE TABLE phksatamoozedata 
( `peksatamoozeiidr` INTEGER,
	`ksatreadingnum` INTEGER,
	`waterdrop` REAL,
	`deltatime` REAL,
	`outflowchamberco` INTEGER,
	`sathydcondmeasur` REAL,
	`steadystateflag` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`peksatamoozedata` INTEGER 
)
CREATE TABLE phksatamoozemeter 
( `phksatsumiidref` INTEGER,
	`repnum` INTEGER,
	`testdate` TEXT,
	`sathydcondrepmea` REAL,
	`sathydcondrepstd` REAL,
	`sathydcondclass` TEXT,
	`boreholedepth` REAL,
	`boreholeradius` REAL,
	`boreholewaterlev` REAL,
	`boreholewaterl_1` REAL,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phksatamoozemete` INTEGER 
)
CREATE TABLE phksatring 
( `phksatsumiidref` TEXT,
	`repnum` TEXT,
	`testdate` TEXT,
	`sathydcondrepmea` TEXT,
	`sathydcondrepstd` TEXT,
	`sathydcondclass` TEXT,
	`ringconfiguratio` TEXT,
	`ringinsertiondep` TEXT,
	`ringradius` TEXT,
	`waterponddepth` TEXT,
	`mariottebottlera` TEXT,
	`texturestructure` TEXT,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`phksatringiid` TEXT 
)
CREATE TABLE phksatringdata 
( `peksatringiidref` TEXT,
	`ksatreadingnum` TEXT,
	`waterdrop` TEXT,
	`deltatime` TEXT,
	`sathydcondmeasur` TEXT,
	`steadystateflag` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`peksatringdataii` TEXT 
)
CREATE TABLE phksatsummary 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`testdate` TEXT,
	`datacollector` TEXT,
	`sathydcondmean` REAL,
	`sathydcondstd` REAL,
	`sathydcondmethod` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`pedonksatsummary` INTEGER 
)
CREATE TABLE phlabresults 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`sampledepthtop` REAL,
	`sampledepthbotto` REAL,
	`sampleid` TEXT,
	`datacollector` TEXT,
	`claytotmeasured` REAL,
	`claycarbmeasured` REAL,
	`silttotmeasured` REAL,
	`siltfinemeasured` REAL,
	`siltcomeasured` REAL,
	`sandtotmeasured` REAL,
	`sandtotmethod` TEXT,
	`sandvcmeasured` REAL,
	`sandcomeasured` REAL,
	`sandmedmeasured` REAL,
	`sandfinemeasured` REAL,
	`sandvfmeasured` REAL,
	`sandvfmethod` TEXT,
	`textureclfieldla` TEXT,
	`fiberrubbedpct` INTEGER,
	`fiberunrubbedpct` INTEGER,
	`ph1to1h2o` REAL,
	`ph01mcacl2` REAL,
	`phnaf` REAL,
	`phoxidized` REAL,
	`phdeltah2o2` TEXT,
	`liquidlimitmeasu` REAL,
	`plasticlimitmeas` REAL,
	`pi` REAL,
	`atterbergsampcon` TEXT,
	`cole` REAL,
	`esttotpotacidity` REAL,
	`camgmeh2` REAL,
	`potassiummeh2` REAL,
	`camgsatpaste` REAL,
	`extractaciditykc` REAL,
	`basesatmeh2` INTEGER,
	`cec7` REAL,
	`cec82` REAL,
	`ecec` REAL,
	`phosphatephos` REAL,
	`nitratenitrogen` REAL,
	`ecmeasured` REAL,
	`ecdeterminemeth` TEXT,
	`ec15` REAL,
	`caco3equivmeasur` INTEGER,
	`gypsumequiv` INTEGER,
	`sodium` REAL,
	`sar` REAL,
	`gypsumreq` INTEGER,
	`humiccolor` TEXT,
	`fulviccolor` TEXT,
	`humicfulviccolor` TEXT,
	`alummeasured` REAL,
	`pyrophoshue` TEXT,
	`pyrophosvalue` INTEGER,
	`pyrophoschroma` INTEGER,
	`melanicindex` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phlabresultiid` INTEGER 
)
CREATE TABLE phmottles 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`mottlepct` INTEGER,
	`mottlesize` TEXT,
	`mottlecntrst` TEXT,
	`colorhue` TEXT,
	`colorvalue` REAL,
	`colorchroma` INTEGER,
	`mottleshape` TEXT,
	`colormoistst` TEXT,
	`mottleloc` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phmottlesiid` INTEGER 
)
CREATE TABLE phorizon 
( `peiidref` INTEGER,
	`seqnum` INTEGER,
	`hzdept` INTEGER,
	`hzdepb` INTEGER,
	`hzthk_l` INTEGER,
	`hzthk_r` INTEGER,
	`hzthk_h` INTEGER,
	`obsmethod` TEXT,
	`hzname` TEXT,
	`hzname_s` INTEGER,
	`desgndisc` INTEGER,
	`desgnmaster` TEXT,
	`desgnmasterprime` TEXT,
	`desgnvert` INTEGER,
	`texture` TEXT,
	`texture_s` INTEGER,
	`stratextsflag` INTEGER,
	`claytotest` REAL,
	`claycarbest` REAL,
	`silttotest` REAL,
	`sandtotest` REAL,
	`fragvoltot` INTEGER,
	`horcolorvflag` INTEGER,
	`obssoimoiststat` TEXT,
	`rupresblkmst` TEXT,
	`rupresblkdry` TEXT,
	`rupresblkcem` TEXT,
	`rupresplate` TEXT,
	`mannerfailure` TEXT,
	`stickiness` TEXT,
	`plasticity` TEXT,
	`toughclass` TEXT,
	`penetrres` TEXT,
	`penetorient` TEXT,
	`ksatpedon` REAL,
	`ksatstddev` REAL,
	`ksatrepnum` INTEGER,
	`horzpermclass` TEXT,
	`obsinfiltrationr` REAL,
	`phfield` REAL,
	`phdetermeth` TEXT,
	`effclass` TEXT,
	`efflocation` TEXT,
	`effagent` TEXT,
	`carbdevstagefe` TEXT,
	`carbdevstagecf` TEXT,
	`mneffclass` TEXT,
	`mneffagent` TEXT,
	`reactadipyridyl` TEXT,
	`dipyridylpct` INTEGER,
	`dipyridylloc` TEXT,
	`excavdifcl` TEXT,
	`soilodor` TEXT,
	`soilodorintensit` TEXT,
	`rmonosulfidep` INTEGER,
	`bounddistinct` TEXT,
	`boundtopo` TEXT,
	`horzvoltotpct_l` INTEGER,
	`horzvoltotpct_r` INTEGER,
	`horzvoltotpct_h` INTEGER,
	`horzlatareapct_l` INTEGER,
	`horzlatareapct_r` INTEGER,
	`horzlatareapct_h` INTEGER,
	`dspcomplayerid` TEXT,
	`aashtocl` TEXT,
	`unifiedcl` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phiid` INTEGER 
)
CREATE TABLE phpores 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`poreqty` REAL,
	`poreqtyclass` TEXT,
	`poresize` TEXT,
	`porecont` TEXT,
	`poreshp` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phporesiid` INTEGER 
)
CREATE TABLE phpvsf 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`pvsfpct` INTEGER,
	`pvsfkind` TEXT,
	`pvsfdistinct` TEXT,
	`pvsfcont` TEXT,
	`pvsflocation` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phpvsfiid` INTEGER 
)
CREATE TABLE phpvsfcolor 
( `phpvsfiidref` INTEGER,
	`seqnum` INTEGER,
	`colorpct` INTEGER,
	`colorhue` TEXT,
	`colorvalue` REAL,
	`colorchroma` INTEGER,
	`colormoistst` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phpvsfcoloriid` INTEGER 
)
CREATE TABLE phrdxfeatures 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`rdxfeatpct` INTEGER,
	`rdxfeatsize` TEXT,
	`rdxfeatcntrst` TEXT,
	`rdxfeathardness` TEXT,
	`rdxfeatshape` TEXT,
	`rdxfeatkind` TEXT,
	`rdxfeatlocation` TEXT,
	`rdxfeatboundary` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phrdxfiid` INTEGER 
)
CREATE TABLE phredoxfcolor 
( `phrdxfiidref` INTEGER,
	`seqnum` INTEGER,
	`colorpct` INTEGER,
	`colorhue` TEXT,
	`colorvalue` REAL,
	`colorchroma` INTEGER,
	`colormoistst` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phrdxfcoloriid` INTEGER 
)
CREATE TABLE phroots 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`rootsquantity` REAL,
	`rootsquantitycla` TEXT,
	`rootssize` TEXT,
	`rootslocation` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phrootsiid` INTEGER 
)
CREATE TABLE phsample 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`labsampnum` TEXT,
	`fldsampid` TEXT,
	`layerdepthtop` INTEGER,
	`layerdepthbottom` INTEGER,
	`numberofbulksamp` INTEGER,
	`numberofbulkdens` INTEGER,
	`numberofnaturalf` INTEGER,
	`numberofothersam` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phlabsampiid` INTEGER 
)
CREATE TABLE phstructure 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`structgrade` TEXT,
	`structsize` TEXT,
	`structtype` TEXT,
	`structid` INTEGER,
	`structpartsto` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phstructureiid` INTEGER 
)
CREATE TABLE phtext 
( `phiidref` TEXT,
	`seqnum` INTEGER,
	`recdate` TEXT,
	`recauthor` TEXT,
	`phorizontextkind` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phtextiid` INTEGER 
)
CREATE TABLE phtexture 
( `phiidref` INTEGER,
	`seqnum` INTEGER,
	`texcl` TEXT,
	`lieutex` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phtiid` INTEGER 
)
CREATE TABLE phtexturemod 
( `phtiidref` INTEGER,
	`seqnum` INTEGER,
	`texmod` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`phtexmodiid` INTEGER 
)
CREATE TABLE phvnirscan 
( `phiidref` TEXT,
	`vnirdepthtop` TEXT,
	`vnirdepthbottom` TEXT,
	`vnirsamplecondit` TEXT,
	`vnirlightsource` TEXT,
	`vnirscandate` TEXT,
	`vnirfilename` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`phvnirscaniid` TEXT 
)
CREATE TABLE phvnirscanresult 
( `phvnirscaniidref` TEXT,
	`vnirmodelid` TEXT,
	`vnirmodelrundate` TEXT,
	`carbontotalpct` TEXT,
	`carboninorganicp` TEXT,
	`carbonorganicpct` TEXT,
	`carbonorganicp_1` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`phvnirscanresult` TEXT 
)
CREATE TABLE plantprodquadratdetails 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`quadratclippedin` TEXT,
	`specieswtairdry` TEXT,
	`specieswtclipped` TEXT,
	`specieswtestimat` TEXT,
	`speciestraceamtf` TEXT,
	`weightunitcount` TEXT,
	`speciescancovpct` TEXT,
	`speciescancovcla` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plantprodquaddet` TEXT 
)
CREATE TABLE plotdisturbance 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`disturbancetype` TEXT,
	`disturbancefrequ` TEXT,
	`disturbanceimpac` TEXT,
	`disturbancelasta` TEXT,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotdisturbancei` TEXT 
)
CREATE TABLE plotgrazinguse 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`animalkind` TEXT,
	`usefrequency` TEXT,
	`seasonofuse` TEXT,
	`stockingratecl` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotgrazinguseii` TEXT 
)
CREATE TABLE plotmainforeststanddetails 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`transectpointloc` TEXT,
	`distancefromprev` TEXT,
	`plantiidref` TEXT,
	`treediameterbrea` TEXT,
	`treeconditions` TEXT,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotmainforstand` TEXT 
)
CREATE TABLE plotplantinventory 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`plantiidref` TEXT,
	`planttypegroup` TEXT,
	`akstratumcovercl` TEXT,
	`plantheightcllow` TEXT,
	`plantheightclupp` TEXT,
	`plantnativity` TEXT,
	`sociabilityclass` TEXT,
	`livecanopyhtbott` TEXT,
	`livecanopyhttop` TEXT,
	`overstorydbhmin` TEXT,
	`overstorydbhmax` TEXT,
	`speciescancovpct` TEXT,
	`speciescancovcla` TEXT,
	`speciestraceamtf` TEXT,
	`speciesbasalarea` TEXT,
	`understorygrcovp` TEXT,
	`understorygrcovc` TEXT,
	`seedlingdensityc` TEXT,
	`maturedensitycla` TEXT,
	`vegetationstrata` TEXT,
	`orderofdominance` TEXT,
	`outsideplotindic` TEXT,
	`estannualprod` TEXT,
	`esdannualprod` TEXT,
	`allowableannualp` TEXT,
	`palatableannualp` TEXT,
	`akfunctionalgrou` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotplantinvento` TEXT 
)
CREATE TABLE plotplanttypecanopycover 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`planttypegroup` TEXT,
	`plantheightcllow` TEXT,
	`plantheightclupp` TEXT,
	`planttypecancovp` TEXT,
	`planttypecancovc` TEXT,
	`cancovassessmeth` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotplanttypecan` TEXT 
)
CREATE TABLE plotsamplingprotocolused 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`plotsampprotocol` TEXT,
	`datacollector` TEXT,
	`datarecorder` TEXT,
	`samplingintensit` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotsampprotoc_1` TEXT 
)
CREATE TABLE plotspeciesbasalarea 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`plantiidref` TEXT,
	`basalareafactor` TEXT,
	`speciesnumbertre` TEXT,
	`speciesbasalarea` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plotspeciebasala` TEXT 
)
CREATE TABLE plottreeinventory 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`plantiidref` TEXT,
	`speciestreecount` TEXT,
	`speciescomppct` TEXT,
	`speciesdbhaverag` TEXT,
	`speciesbasalarea` TEXT,
	`plottreeinventor` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT 
)
CREATE TABLE plottreescounted 
( `plottreeinventor` TEXT,
	`seqnum` TEXT,
	`dbhclassmidpoint` TEXT,
	`dbhclassspeciest` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plottreescounted` TEXT 
)
CREATE TABLE plottreesiteindexdetails 
( `plottreesiteinds` TEXT,
	`seqnum` TEXT,
	`treenumber` TEXT,
	`crownclass` TEXT,
	`reproductionsour` TEXT,
	`treediameterbrea` TEXT,
	`tenyeargrowthrad` TEXT,
	`growthringcount` TEXT,
	`growthringcounth` TEXT,
	`growthringcounta` TEXT,
	`treeage` TEXT,
	`treecanopyhtbott` TEXT,
	`treecanopyhttop` TEXT,
	`aknoringsinlasti` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plottreesiteindd` TEXT 
)
CREATE TABLE plottreesiteindexsummary 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`plantiidref` TEXT,
	`plantnativity` TEXT,
	`siteindexbase` TEXT,
	`speciestreecount` TEXT,
	`siteindexplotave` TEXT,
	`speciesdbhaverag` TEXT,
	`treeageave` TEXT,
	`treecanopyhttopa` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plottreesiteinds` TEXT 
)
CREATE TABLE plottreesummary 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`dbhclassmidpoint` TEXT,
	`dbhclasstreecoun` TEXT,
	`dbhclassbasalare` TEXT,
	`dbhclasstreedens` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`plottreesummaryi` TEXT 
)
CREATE TABLE pointplantcoverdetails 
( `vegtransplantsum` TEXT,
	`seqnum` TEXT,
	`transectpointloc` TEXT,
	`livecanopyhtbott` TEXT,
	`livecanopyhttop` TEXT,
	`canopycoverprese` TEXT,
	`foliarcoverprese` TEXT,
	`basalcoverpresen` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`pointplantcovdet` TEXT 
)
CREATE TABLE site 
( `usiteid` TEXT,
	`latdegrees` INTEGER,
	`latminutes` INTEGER,
	`latseconds` REAL,
	`latdir` TEXT,
	`longdegrees` INTEGER,
	`longminutes` INTEGER,
	`longseconds` REAL,
	`longdir` TEXT,
	`horizdatnm` TEXT,
	`locdesc` TEXT,
	`plsssdetails` TEXT,
	`plsssection` INTEGER,
	`plsstownship` TEXT,
	`plssrange` TEXT,
	`plssmeridian` TEXT,
	`utmzone` INTEGER,
	`utmnorthing` REAL,
	`utmeasting` REAL,
	`geocoordsource` TEXT,
	`elev` REAL,
	`geomposhill` TEXT,
	`geomposmntn` TEXT,
	`geompostrce` TEXT,
	`geomposflats` TEXT,
	`hillslopeprof` TEXT,
	`geomslopeseg` TEXT,
	`slope` REAL,
	`aspect` INTEGER,
	`slopelenusle` INTEGER,
	`slopelenuptro` REAL,
	`shapeacross` TEXT,
	`shapedown` TEXT,
	`slopecomplex` TEXT,
	`locphysnm` TEXT,
	`siteksatclassupp` TEXT,
	`siteksatclasslow` TEXT,
	`drainagecl` TEXT,
	`runoff` TEXT,
	`drainagepattern` TEXT,
	`pmgroupname` TEXT,
	`pmgroupname_s` INTEGER,
	`climstaid` TEXT,
	`climstanm` TEXT,
	`climstatype` TEXT,
	`ffd` INTEGER,
	`map` INTEGER,
	`reannualprecip` INTEGER,
	`airtempa` REAL,
	`soiltempa` REAL,
	`airtemps` REAL,
	`soiltemps` REAL,
	`airtempw` REAL,
	`soiltempw` REAL,
	`benchmarksoilfla` INTEGER,
	`flodfreqcl` TEXT,
	`floddurcl` TEXT,
	`flodmonthbeg` TEXT,
	`pondfreqcl` TEXT,
	`ponddurcl` TEXT,
	`pondmonthbeg` TEXT,
	`wtabledur` INTEGER,
	`latstddecimaldeg` REAL,
	`longstddecimalde` REAL,
	`gpspositionalerr` REAL,
	`gpspdop` INTEGER,
	`elevcorrected` REAL,
	`sdbiidref` INTEGER,
	`siteiid` INTEGER 
)
CREATE TABLE siteaoverlap 
( `seqnum` INTEGER,
	`areaiidref` INTEGER,
	`siteiidref` INTEGER,
	`sareaoviid` INTEGER,
	`areaname` TEXT,
	`areasymbol` TEXT,
	`areatypename` TEXT 
)
CREATE TABLE siteassoc 
( `usiteassocid` TEXT,
	`sadbiidref` TEXT,
	`siteassociid` TEXT 
)
CREATE TABLE siteassocsite 
( `seqnum` TEXT,
	`siteiidref` TEXT,
	`siteassociidref` TEXT,
	`siteasiteiid` TEXT 
)
CREATE TABLE siteassocsoi 
( `seqnum` INTEGER,
	`assocsoi` TEXT,
	`siteiidref` INTEGER,
	`siteassocsoiiid` INTEGER 
)
CREATE TABLE siteassoctext 
( `seqnum` TEXT,
	`recdate` TEXT,
	`recauthor` TEXT,
	`siteassoctextkin` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`siteassociidref` TEXT,
	`siteatextiid` TEXT 
)
CREATE TABLE sitebedrock 
( `seqnum` INTEGER,
	`bedrockorder` INTEGER,
	`geogroup` TEXT,
	`geoform` TEXT,
	`geomember` TEXT,
	`bedrckdepth` INTEGER,
	`bedrckkind` TEXT,
	`bedrckhardness` TEXT,
	`bedrckfractint` TEXT,
	`bedrckweather` TEXT,
	`bedrckstrike` INTEGER,
	`bedrckdip_l` INTEGER,
	`bedrckdip_h` INTEGER,
	`siteiidref` INTEGER,
	`sitebedrockiid` INTEGER 
)
CREATE TABLE siteecositehistory 
( `ecositecorrdate` TEXT,
	`classifier` TEXT,
	`ecositeiidref` INTEGER,
	`siteiidref` INTEGER,
	`siteecositehisto` INTEGER 
)
CREATE TABLE siteerosionacc 
( `seqnum` INTEGER,
	`erokind` TEXT,
	`siteobsiidref` INTEGER,
	`siteeroacciid` INTEGER 
)
CREATE TABLE sitegeomordesc 
( `seqnum` INTEGER,
	`geomfiidref` INTEGER,
	`geomfmod` TEXT,
	`geomfeatid` INTEGER,
	`existsonfeat` INTEGER,
	`siteiidref` INTEGER,
	`sitegeomdiid` INTEGER 
)
CREATE TABLE siteiristubedata 
( `siteobsiidref` INTEGER,
	`iristubeid` INTEGER,
	`topdepthevaluate` REAL,
	`bottomdepthevalu` REAL,
	`dateinstalled` TEXT,
	`dateremoved` TEXT,
	`ironpctremoved` INTEGER,
	`reducedsoilflag` INTEGER,
	`irisimagefilenam` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`siteiristubedata` INTEGER 
)
CREATE TABLE sitemuoverlap 
( `siteiidref` INTEGER,
	`seqnum` INTEGER,
	`lmapunitiidref` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`smuoviid` INTEGER 
)
CREATE TABLE siteobs 
( `seqnum` INTEGER,
	`obsdate` TEXT,
	`obsdatekind` TEXT,
	`datacollector` TEXT,
	`photoid` TEXT,
	`swaterkind` TEXT,
	`swaterdepth` INTEGER,
	`hydrologystatus` TEXT,
	`geomicrorelief` TEXT,
	`geommicelev` INTEGER,
	`geommicpat` TEXT,
	`ecostateid` INTEGER,
	`ecostatename` TEXT,
	`commphaseid` INTEGER,
	`commphasename` TEXT,
	`plantassocnm` TEXT,
	`earthcovkind1` TEXT,
	`earthcovkind2` TEXT,
	`resourceretentio` TEXT,
	`bareareamaxwidth` INTEGER,
	`pedodermclass` TEXT,
	`pedodermcovind` INTEGER,
	`biolcrusttypedom` TEXT,
	`biolcrusttypesec` TEXT,
	`physcrustsubtype` TEXT,
	`crustdevcl` TEXT,
	`soilredistributi` TEXT,
	`exposedsoilpct` INTEGER,
	`localdisturbance` INTEGER,
	`localdisturban_1` TEXT,
	`drainedflag` INTEGER,
	`beddingflag` INTEGER,
	`plantationflag` INTEGER,
	`forestrotationst` TEXT,
	`yldstudyid` TEXT,
	`currweathcond` TEXT,
	`currairtemp` INTEGER,
	`tidalperiod` TEXT,
	`bottomtype` TEXT,
	`saswatertempuppe` INTEGER,
	`saswatertemplowe` INTEGER,
	`saswaterphupper` REAL,
	`saswaterphlower` REAL,
	`phdetermeth` TEXT,
	`sasdissolvedoxyu` REAL,
	`sasdissolvedoxyl` REAL,
	`saswatersalinity` REAL,
	`saswatersalini_1` REAL,
	`siteiidref` INTEGER,
	`siteobsiid` INTEGER 
)
CREATE TABLE siteobstext 
( `seqnum` INTEGER,
	`recdate` TEXT,
	`recauthor` TEXT,
	`siteobstextkind` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`siteobsiidref` INTEGER,
	`siteobstextiid` INTEGER 
)
CREATE TABLE siteothvegclass 
( `siteiidref` INTEGER,
	`seqnum` INTEGER,
	`ovegcliidref` INTEGER,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`siteovegcliid` INTEGER 
)
CREATE TABLE sitepm 
( `seqnum` INTEGER,
	`pmorder` INTEGER,
	`pmdept` INTEGER,
	`pmdepb` INTEGER,
	`pmmodifier` TEXT,
	`pmgenmod` TEXT,
	`pmkind` TEXT,
	`pmorigin` TEXT,
	`pmweathering` TEXT,
	`siteiidref` INTEGER,
	`sitepmiid` INTEGER 
)
CREATE TABLE sitesoilmoist 
( `seqnum` INTEGER,
	`soimoistdept` INTEGER,
	`soimoistdepb` INTEGER,
	`soilmoistsensord` REAL,
	`soilmoistsensork` TEXT,
	`obssoimoiststat` TEXT,
	`obssoimoist` INTEGER,
	`obsgrsoimoist` INTEGER,
	`soimoistten` REAL,
	`siteobsiidref` INTEGER,
	`sitesmiid` INTEGER 
)
CREATE TABLE sitesoiltemp 
( `seqnum` INTEGER,
	`soitempdep` INTEGER,
	`soiltempsensorki` TEXT,
	`soitemp` REAL,
	`siteobsiidref` INTEGER,
	`sitestiid` INTEGER 
)
CREATE TABLE sitesurffrags 
( `seqnum` INTEGER,
	`sfragcov` REAL,
	`distrocks` REAL,
	`sfragkind` TEXT,
	`sfragsize_l` INTEGER,
	`sfragsize_r` INTEGER,
	`sfragsize_h` INTEGER,
	`sfragshp` TEXT,
	`sfraground` TEXT,
	`sfraghard` TEXT,
	`siteobsiidref` INTEGER,
	`sitesurffragsiid` INTEGER 
)
CREATE TABLE sitetext 
( `seqnum` INTEGER,
	`recdate` TEXT,
	`recauthor` TEXT,
	`sitetextkind` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`siteiidref` INTEGER,
	`sitetextiid` INTEGER 
)
CREATE TABLE sitetreescounted 
( `sitewoodybasalar` TEXT,
	`seqnum` TEXT,
	`treediameterbrea` TEXT,
	`treeheight` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`treescountediid` TEXT 
)
CREATE TABLE siteusgsquadrangleoverlap 
( `siteiidref` TEXT,
	`seqnum` TEXT,
	`usgsquadrangleii` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`siteusgsquadovii` TEXT 
)
CREATE TABLE sitewoodybasalarea 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`basalareafactor` TEXT,
	`numberoftreesin` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`sitewoodybasalar` TEXT 
)
CREATE TABLE soilmoistmonitordata 
( `soilmonitordatai` INTEGER,
	`sensorid` INTEGER,
	`soilmoistsensord` REAL,
	`soilmoistsensork` TEXT,
	`soilmoistvoldail` REAL,
	`soilmoistvolda_1` REAL,
	`soilmoistvolda_2` REAL,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`soilmoistmonitor` INTEGER 
)
CREATE TABLE soilmonitordata 
( `peiidref` INTEGER,
	`stationid` TEXT,
	`obsdate` TEXT,
	`dailyprecipmeasu` REAL,
	`airtempmin` REAL,
	`airtempave` REAL,
	`airtempmax` REAL,
	`airtempsensorhei` INTEGER,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`soilmonitordatai` INTEGER 
)
CREATE TABLE soiltempmonitordata 
( `soilmonitordatai` INTEGER,
	`sensorid` INTEGER,
	`soiltempsensorde` REAL,
	`soiltempsensorki` TEXT,
	`soiltempdailymin` REAL,
	`soiltempdailyave` REAL,
	`soiltempdailymax` REAL,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` INTEGER,
	`soiltempmonitord` INTEGER 
)
CREATE TABLE subplotplantdetails 
( `plotplantinvento` TEXT,
	`seqnum` TEXT,
	`subplotnumber` TEXT,
	`subplotsize` TEXT,
	`stemcount` TEXT,
	`stemdiameteraver` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`subplotplantdeta` TEXT 
)
CREATE TABLE totalquadratharvest 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`quadrattotwtclip` TEXT,
	`recuseriidref` TEXT,
	`recwlupdated` TEXT,
	`totalquadratharv` TEXT 
)
CREATE TABLE transect 
( `utransectid` TEXT,
	`tsectauth` TEXT,
	`tsectkind` TEXT,
	`tsectselmeth` TEXT,
	`tsectdelinsize` INTEGER,
	`tsectdir` INTEGER,
	`tsectcertstatus` TEXT,
	`tsectdbiidref` INTEGER,
	`tsectiid` INTEGER 
)
CREATE TABLE transectestcomposition 
( `seqnum` INTEGER,
	`compname` TEXT,
	`localphase` TEXT,
	`comppct` INTEGER,
	`slope_l` REAL,
	`slope_h` REAL,
	`tsectiidref` INTEGER,
	`tsectestcompiid` INTEGER 
)
CREATE TABLE transectgapdetails 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`gapnumber` TEXT,
	`gapkind` TEXT,
	`gapstartpoint` TEXT,
	`gapendpoint` TEXT,
	`gaplength` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transectgapdetai` TEXT 
)
CREATE TABLE transectgroundcover 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`groundcovertype` TEXT,
	`groundcoverptcou` TEXT,
	`groundcoverptpct` TEXT,
	`quadratsize` TEXT,
	`quadratshape` TEXT,
	`groundcoverquadp` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transectgroundco` TEXT 
)
CREATE TABLE transectgroundcoverdatalegacy 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`quadratbaregrpct` TEXT,
	`quadratcancovpct` TEXT,
	`quadratrockfragc` TEXT,
	`quadratmulchwt` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transgrcovlegacy` TEXT 
)
CREATE TABLE transectgroundsurfcover 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`groundsurfcovtyp` TEXT,
	`groundcoverptcou` TEXT,
	`groundcoverptpct` TEXT,
	`quadratsize` TEXT,
	`quadratshape` TEXT,
	`groundcoverquadp` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transectgroundsu` TEXT 
)
CREATE TABLE transectoverstorycanopycover 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`transectpointloc` TEXT,
	`overstorycanopyp` TEXT,
	`densiometerquads` TEXT,
	`overstorycancovp` TEXT,
	`overstorycancovc` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transoverstoryca` TEXT 
)
CREATE TABLE transectsamplingprotocolused 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`transsampprotoco` TEXT,
	`datacollector` TEXT,
	`datarecorder` TEXT,
	`samplingintensit` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transsampproto_1` TEXT 
)
CREATE TABLE transectstandingbiomassdetails 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`quadratnumber` TEXT,
	`transectpointloc` TEXT,
	`quadratsize` TEXT,
	`quadratshape` TEXT,
	`herbbiomasswtgre` TEXT,
	`herbbiomasswtair` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`transstandbiomas` TEXT 
)
CREATE TABLE transecttext 
( `seqnum` INTEGER,
	`recdate` TEXT,
	`recauthor` TEXT,
	`transecttextkind` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`tsectiidref` INTEGER,
	`transecttextiid` INTEGER 
)
CREATE TABLE vegplot 
( `siteobsiidref` TEXT,
	`vegplotid` TEXT,
	`vegplotname` TEXT,
	`primarydatacolle` TEXT,
	`datacollectionpu` TEXT,
	`vegdataorigin` TEXT,
	`vegplotsize` TEXT,
	`soilprofileindic` TEXT,
	`assocuserpedonid` TEXT,
	`soil232idlegacy` TEXT,
	`ahorizondepth` TEXT,
	`alkalinesalinein` TEXT,
	`alkalineaffected` TEXT,
	`salinityclass` TEXT,
	`restrictivelayer` TEXT,
	`legacysoilcompna` TEXT,
	`legacysoilphase` TEXT,
	`legacylocalsoilp` TEXT,
	`legacysoilsurfte` TEXT,
	`legacysurftextmo` TEXT,
	`legacyterminlieu` TEXT,
	`erosionclasslega` TEXT,
	`landformgroupleg` TEXT,
	`cryptogamcovclle` TEXT,
	`rangelandusehist` TEXT,
	`cancovpctplotave` TEXT,
	`cancovtotalpct` TEXT,
	`cancovtotalclass` TEXT,
	`overstorycancont` TEXT,
	`overstorycancovt` TEXT,
	`dblsampannualpro` TEXT,
	`compyieldproduct` TEXT,
	`abovegroundbioma` TEXT,
	`understoryreprod` TEXT,
	`woodyunderstorya` TEXT,
	`herbundertoryabu` TEXT,
	`lichensunderstor` TEXT,
	`crowncanclosurep` TEXT,
	`crowncancloseass` TEXT,
	`crowncompfactorl` TEXT,
	`crowncomplppaved` TEXT,
	`basalcoverpctave` TEXT,
	`basalareaplottot` TEXT,
	`basalareaassessm` TEXT,
	`constreeshrubgrp` TEXT,
	`windbreakrowoned` TEXT,
	`windbreaktrapped` TEXT,
	`windbreaktrapp_1` TEXT,
	`understorydescin` TEXT,
	`mensurationdatai` TEXT,
	`vigorclasslegacy` TEXT,
	`siteconditionleg` TEXT,
	`overstoryspecies` TEXT,
	`plantmoiststate` TEXT,
	`currenttreedensi` TEXT,
	`currenttreespaci` TEXT,
	`currentdxspacing` TEXT,
	`currentplotavedb` TEXT,
	`plotbasalareafac` TEXT,
	`currentbasalarea` TEXT,
	`foreststandtype` TEXT,
	`foreststratainve` TEXT,
	`foreststandregen` TEXT,
	`foreststandquali` TEXT,
	`desiredtreedensi` TEXT,
	`desireddxspacing` TEXT,
	`desiredbasalarea` TEXT,
	`excessbasalarea` TEXT,
	`excesstreedensit` TEXT,
	`stockingchangepc` TEXT,
	`treepctgoodcondi` TEXT,
	`treepctfaircondi` TEXT,
	`treepctpoorcondi` TEXT,
	`treecounttotal` TEXT,
	`treesnagdensityh` TEXT,
	`treesnagdensitys` TEXT,
	`rhiannualprod` TEXT,
	`rhibareground` TEXT,
	`rhicompactionlay` TEXT,
	`rhifuncstructgro` TEXT,
	`rhierosionresist` TEXT,
	`rhigullies` TEXT,
	`rhirills` TEXT,
	`rhipedastalsterr` TEXT,
	`rhiinfilrunoff` TEXT,
	`rhilitteramount` TEXT,
	`rhilittermovemen` TEXT,
	`rhiplantmortalit` TEXT,
	`rhireprodcapabil` TEXT,
	`rhiinvasiveplant` TEXT,
	`rhisoilsurfdegra` TEXT,
	`rhiwaterflowpatt` TEXT,
	`rhiwindscourarea` TEXT,
	`rhisoilsitestabs` TEXT,
	`rhibioticintegri` TEXT,
	`rhihydrofunction` TEXT,
	`pastureforagetyp` TEXT,
	`pasturestanddens` TEXT,
	`pastureplanthtav` TEXT,
	`pastureprodave` TEXT,
	`pcidesirableplan` TEXT,
	`pciplantcover` TEXT,
	`pciplantdiversit` TEXT,
	`pcigroundcovresi` TEXT,
	`pcistandingdeadf` TEXT,
	`pciplantresiduec` TEXT,
	`pciplantvigor` TEXT,
	`pcilegumepctclas` TEXT,
	`pciuseuniformity` TEXT,
	`pcilivestockconc` TEXT,
	`pcisoilcompactio` TEXT,
	`pcisheetrilleros` TEXT,
	`pciwinderosion` TEXT,
	`pcistreamshoreer` TEXT,
	`pcigullyerosion` TEXT,
	`pcierosioncompsc` TEXT,
	`pcipasturecondit` TEXT,
	`refplantcommunit` TEXT,
	`repannualprod` TEXT,
	`totestannualprod` TEXT,
	`totallowableannu` TEXT,
	`totpalatableannu` TEXT,
	`similarityindex` TEXT,
	`annualuseablepro` TEXT,
	`harvesteffpct` TEXT,
	`takehalfleavehal` TEXT,
	`acresperaum` TEXT,
	`aumperacre` TEXT,
	`audperacre` TEXT,
	`desirableplantvi` TEXT,
	`desirableseedlin` TEXT,
	`decadentplantabu` TEXT,
	`plantresidueadeq` TEXT,
	`undesirableinvad` TEXT,
	`majorinvadingspe` TEXT,
	`invadingspeciesc` TEXT,
	`soilsurferosion` TEXT,
	`soilcrusting` TEXT,
	`soilcompaction` TEXT,
	`baregroundpct` TEXT,
	`gullyrillpresenc` TEXT,
	`soildegradationr` TEXT,
	`rangetrendcurren` TEXT,
	`rangetrendplanne` TEXT,
	`qcreviewperson` TEXT,
	`qcreviewdate` TEXT,
	`qareviewperson` TEXT,
	`qareviewdate` TEXT,
	`swcdlegacy` TEXT,
	`fieldofficelegac` TEXT,
	`nrcsarealegacy` TEXT,
	`aktotallichencov` TEXT,
	`aktotallitter1co` TEXT,
	`aktotallitter2co` TEXT,
	`aktotalmosscover` TEXT,
	`aktotalrockcover` TEXT,
	`aktotalsoilcover` TEXT,
	`aktotalwatercove` TEXT,
	`akecologicalsite` TEXT,
	`aktotalbedrockco` TEXT,
	`akfieldecositeid` TEXT,
	`vegplotdbiidref` TEXT,
	`grpiidref` TEXT,
	`objwlupdated` TEXT,
	`objuseriidref` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`vegplotiid` TEXT 
)
CREATE TABLE vegplottext 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`recdate` TEXT,
	`recauthor` TEXT,
	`vegplottextkind` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`vegplottextiid` TEXT 
)
CREATE TABLE vegtransect 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`vegtransectid` TEXT,
	`transectstartlat` TEXT,
	`transectstartlon` TEXT,
	`transectendlatit` TEXT,
	`transectendlongi` TEXT,
	`transectazimuth` TEXT,
	`transectlength` TEXT,
	`transectstartele` TEXT,
	`transectendeleva` TEXT,
	`dblsampquadratss` TEXT,
	`dblsampquadratsc` TEXT,
	`nestedfreqquadra` TEXT,
	`freqquadratssamp` TEXT,
	`dwrquadratssampl` TEXT,
	`daubenmirequadra` TEXT,
	`quadratsizedomle` TEXT,
	`quadratsizesecle` TEXT,
	`quadratshapedoml` TEXT,
	`quadratshapesecl` TEXT,
	`beltwidth` TEXT,
	`dblsampannualpro` TEXT,
	`totharvestannual` TEXT,
	`wtunitannualprod` TEXT,
	`dwrannualprod` TEXT,
	`comparativeyield` TEXT,
	`comparativeyie_1` TEXT,
	`comparativeyie_2` TEXT,
	`comparativerefcl` TEXT,
	`abovegroundbioma` TEXT,
	`standingherbbiom` TEXT,
	`transectbasalcov` TEXT,
	`basalcovpcttotal` TEXT,
	`basalgapsizemin` TEXT,
	`canopygapsizemin` TEXT,
	`gapsmeasuredbetw` TEXT,
	`canopygaplengtht` TEXT,
	`canopygappcttota` TEXT,
	`basalgaplengthto` TEXT,
	`basalgappcttotal` TEXT,
	`understoryreprod` TEXT,
	`woodyunderstorya` TEXT,
	`herbundertoryabu` TEXT,
	`lichensunderstor` TEXT,
	`cancovpcttotaltr` TEXT,
	`cancovtotalclass` TEXT,
	`cancovassessmeth` TEXT,
	`crowncanclosurep` TEXT,
	`crowncancloseass` TEXT,
	`crowncompfactorl` TEXT,
	`crowncomplppaved` TEXT,
	`overstorycancovp` TEXT,
	`overstorycancovc` TEXT,
	`groundcovassessm` TEXT,
	`groundcovquadrat` TEXT,
	`groundcovpointss` TEXT,
	`groundsurfcovass` TEXT,
	`groundsurfcovqua` TEXT,
	`groundsurfcovpoi` TEXT,
	`lpiobsinterval` TEXT,
	`totalpointssampl` TEXT,
	`topcanopyhtave` TEXT,
	`topcanopyhtstdde` TEXT,
	`totalnumplantsbe` TEXT,
	`totalnumspeciesb` TEXT,
	`totalplantdensit` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`vegtransectiid` TEXT 
)
CREATE TABLE vegtransectplantsummary 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`plantiidref` TEXT,
	`plantnativity` TEXT,
	`planttypegroup` TEXT,
	`plantheightcllow` TEXT,
	`plantheightclupp` TEXT,
	`sociabilityclass` TEXT,
	`specieslivecanht` TEXT,
	`specieslivecan_1` TEXT,
	`overstorydbhmin` TEXT,
	`overstorydbhmax` TEXT,
	`speciesovercanco` TEXT,
	`speciesovercan_1` TEXT,
	`plantprodquadrat` TEXT,
	`plantprodquadr_1` TEXT,
	`nestedfreqquadra` TEXT,
	`nestedfreqquad_1` TEXT,
	`frequencyquadrat` TEXT,
	`frequencyquadr_1` TEXT,
	`dwrquadratsize` TEXT,
	`dwrquadratshape` TEXT,
	`densityquadratsi` TEXT,
	`densityquadratsh` TEXT,
	`speciestotwtclip` TEXT,
	`speciestotwtcl_1` TEXT,
	`speciestotwtcl_2` TEXT,
	`speciestotwtaird` TEXT,
	`speciestotwtest` TEXT,
	`speciestotwtexis` TEXT,
	`speciesdrywtpct` TEXT,
	`speciestotwt` TEXT,
	`speciesaveyieldd` TEXT,
	`speciescomppctdb` TEXT,
	`speciescomppctda` TEXT,
	`speciescomppctli` TEXT,
	`speciestraceamtf` TEXT,
	`weightconvfactor` TEXT,
	`dblsampcorrectio` TEXT,
	`airdrywtadjustme` TEXT,
	`utilizationadjus` TEXT,
	`growthadjustment` TEXT,
	`weatheradjustmen` TEXT,
	`numberofquadrats` TEXT,
	`speciesfreqdaube` TEXT,
	`dwronetally` TEXT,
	`dwrtwotally` TEXT,
	`dwrthreetally` TEXT,
	`dwrweightedtally` TEXT,
	`speciescomppctdw` TEXT,
	`speciesaveyiel_1` TEXT,
	`wtunitweight` TEXT,
	`wtunitcounttotal` TEXT,
	`speciesaveyieldw` TEXT,
	`wtunitwtclippedt` TEXT,
	`speciescancovhit` TEXT,
	`speciescancovpct` TEXT,
	`speciescancovp_1` TEXT,
	`speciescancovave` TEXT,
	`speciesfoliarcov` TEXT,
	`speciesfoliarc_1` TEXT,
	`speciestotfoliar` TEXT,
	`speciesbasalcovh` TEXT,
	`speciesbasalcovp` TEXT,
	`speciestotbasalc` TEXT,
	`maturecounttotal` TEXT,
	`maturedensityave` TEXT,
	`maturedensitya_1` TEXT,
	`seedlingcounttot` TEXT,
	`seedlingdensitya` TEXT,
	`seedlingdensit_1` TEXT,
	`speciesgroundcov` TEXT,
	`speciescancovpor` TEXT,
	`speciesbasalarea` TEXT,
	`basalareaassessm` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`vegtransplantsum` TEXT 
)
CREATE TABLE vegtransecttext 
( `vegtransectiidre` TEXT,
	`seqnum` TEXT,
	`recdate` TEXT,
	`recauthor` TEXT,
	`vegtransecttextk` TEXT,
	`textcat` TEXT,
	`textsubcat` TEXT,
	`textentry` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`vegtranstextiid` TEXT 
)
CREATE TABLE windbreakrowdata 
( `vegplotiidref` TEXT,
	`seqnum` TEXT,
	`windbreakrowid` TEXT,
	`plantiidref` TEXT,
	`growingseasoncou` TEXT,
	`speiescondition` TEXT,
	`crownspreadleft` TEXT,
	`crownspreadright` TEXT,
	`spacingbetweenro` TEXT,
	`spacingwithinrow` TEXT,
	`cultivationpast` TEXT,
	`cultivationprese` TEXT,
	`speciesdbhaverag` TEXT,
	`diseasekind` TEXT,
	`diseasedamagedeg` TEXT,
	`injurykind` TEXT,
	`injurydamagedegr` TEXT,
	`insectkind` TEXT,
	`insectdamagedegr` TEXT,
	`groundcoverexten` TEXT,
	`heightlivecrownl` TEXT,
	`heightlivecrownr` TEXT,
	`survivalpct` TEXT,
	`windbreakrowhtav` TEXT,
	`windbreakrowhtma` TEXT,
	`reprodabundancec` TEXT,
	`rootdepthfew` TEXT,
	`rootdepthcommon` TEXT,
	`rootdepthmany` TEXT,
	`suppressiondegre` TEXT,
	`suppressionrowle` TEXT,
	`suppressiondeg_1` TEXT,
	`suppressionrowri` TEXT,
	`vitalnotesindica` TEXT,
	`soiltaxonrangein` TEXT,
	`notes` TEXT,
	`recwlupdated` TEXT,
	`recuseriidref` TEXT,
	`windbreakrowdata` TEXT 
)
