---
title: "Introduction to SoilProfileCollection Objects"
author: "D.E. Beaudette"
date: "`r Sys.Date()`"
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, echo=FALSE, results='hide', warning=FALSE}
library(knitr, quietly=TRUE)

opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  background = '#F7F7F7', 
  fig.align = 'center', 
  dev = 'svglite', 
  fig.ext = ".svg", 
  tidy = FALSE, 
  verbose = FALSE
)

options(width=100, stringsAsFactors=FALSE)
```

```{r}
library(soilDB)
library(aqp)


SDA_query("SELECT TOP 10 * FROM lab_area WHERE area_type = 'ssa' ;")

SDA_query("SELECT DISTINCT area_type FROM lab_area ;")

SDA_query("SELECT TOP 1 * FROM lab_pedon ;")

SDA_query("SELECT TOP 1 * FROM lab_layer ;")

x <- SDA_query("SELECT TOP 1 * FROM lab_physical_properties ;")
str(x)

# lab_pedon -> lab_layer [pedon_key]
# lab_layer -> lab_physical_properties [labsampnum]


## CA792 site/pedon IDs + coordinates

sql <- "
SELECT
pedon_key, pedlabsampnum, pedoniid, upedonid, longitude_decimal_degrees, latitude_decimal_degrees,
area_code
FROM
lab_combine_nasis_ncss
JOIN
lab_area ON area_key = ssa_key AND area_type = 'ssa'
WHERE area_code = 'CA792'
;"

pedons <- SDA_query(sql)
nrow(pedons)
head(pedons)


# make a quoted vector of pedon keys, for use in the next query
pedon.keys <- format_SQL_in_statement(pedons$pedon_key)


## CA792 layer + physical properties
sql <- sprintf("
SELECT
l.pedon_key, l.labsampnum, hzn_top, hzn_bot, hzn_desgn,
sand_total, silt_total, clay_total, particle_size_method,
ph_h2o
FROM
lab_layer AS l
JOIN lab_physical_properties AS p ON l.labsampnum = p.labsampnum
JOIN lab_chemical_properties AS c ON l.labsampnum = c.labsampnum
WHERE l.pedon_key IN %s
ORDER BY l.pedon_key, hzn_top
;", pedon.keys)

hz <- SDA_query(sql)
nrow(hz)
head(hz)

# unique set of methods
table(hz$particle_size_method)

# join pedon + horizon data


## just for fun, use a function from aqp to show texture variation
ssc <- na.omit(hz[, c('sand_total', 'silt_total', 'clay_total')])
names(ssc) <- c('SAND', 'SILT', 'CLAY')

textureTriangleSummary(ssc, cex = 0.5)
```

